const YNOptions = {
    labels: ['Yes', 'No'],
    values: ['Y', 'N']
}

const racOptions = {
    labels: [
        'A1 - Foster care Medicaid, Title IVE ',
        'A18 - Foster Care Independent Living Medicaid, age 18 through 20',
        'A19 - Former Foster Care Medicaid, 18 to 26',
        'A1A - Subsidized adoption Medicaid, Title IV-E',
        'A21 - Family Medicaid - Adult (AFDC)',
        'A22 - Family Medicaid - Child (LIFC)',
        'A23 - Family Medicaid - Adult (AFDC)',
        'A31 - Family Medicaid - Adult (AFDC)',
        'A32 - Family Medicaid - Child (LIFC)',
        'A35 - Family Medicaid - Child (LIFC)',
        'A36 - Family Medicaid, Adult Parent/ Caretaker Relative',
        'A37 - Family Medicaid, Adult Parent/ Caretaker Relative ',
        'A4 - Family Medicaid - Child (AFDC)',
        'A42 - Adult, Medicaid, Chronically Homeless Individuals',
        'A43 - Adult Medicaid, Justice Involved Individuals',
        'A44 - Adult Medicaid, Individuals Needing Substance Abuse or Mental Health Treatment',
        'A5 - Family Medicaid - Child (AFDC)',
        'A51 - Family Medicaid, Adult, 4-month spousal support increase',
        'A52 - Family Medicaid, Child, 4-month spousal support increase',
        'A55 - Family Medicaid, Child, 12-month transitional earned income increase',
        'A57 - Family Medicaid, Adult, 12-month transitional earned income increase',
        'A61 - Family Medicaid - Adult (4 Month Extension)',
        'A62 - Family Medicaid - Child (4 month Transitional-Earned Income increase)',
        'A63 - Family Medicaid - Adult (9 Month Extension)',
        'A64 - Family – Child, 9 month Transitional-exhausted time frame for $30 or 1/3 earned income disregard',
        'A65 - Family Medicaid - Child (12 month Transitional-Earned Income increase)',
        'A66 - Child Medicaid (< 2 months of age born to mom on Medicaid)',
        'A67 - Child Medicaid (< 3 months of age born to mom on Medicaid)',
        'A68 - Family Medicaid - Adult (12 Month Extension)',
        'A69 - Child Medicaid, 0 to 1, born to a mom on Medicaid',
        'A7 - Pregnant Woman Medicaid, Spenddown',
        'A8 - Family Medicaid - Child (AFDC)',
        'A80 - Child Medicaid, ages 6 through 18',
        'A81 - Child Medicaid, ages 0 through 5',
        'A82 - Pregnant Woman Medicaid - 139% FPL',
        'A83 - Nursing Home Medicaid - Child -ancillary only',
        'A84 - Nursing Home Medicaid - Pregnant - ancillary only',
        'A94 - Nursing Home Medicaid - Aged SSI or Protected group',
        'A95 - Nursing Home Medicaid, Aged, ancillary only',
        'AA4 - Nursing Home Medicaid, Blind SSI and Protected groups',
        'AA5 - Nursing Home Medicaid, Blind and Protected groups, ancillary only',
        'AB4 - Nursing Home Medicaid, Disabled SSI and Protected groups',
        'AB5 - Nursing Home Medicaid, Disabled, ancillary only ',
        'ABF - Foster Care Medicaid, Blind, non IVE, SSI or Protected groups ',
        'AC3 - Aged Medicaid - SSI',
        'AC4 - Aged Medicaid (SSI)',
        'AC8 - Aged Medicaid - 1619b',
        'AC9 - Aged Medicaid - Pickle Amendment',
        'ACF - Foster Care Medicaid (non-IVE, ages 6-18) ',
        'AD1 - Blind Medicaid, SSI',
        'AD2 - Blind Medicaid (SSI)',
        'AD8 - Blind Medicaid, 1619(b)',
        'AD9 - Blind Medicaid, Pickle Amendment',
        'ADF - Foster Care Medicaid, non-IVE, Disabled-SSI or SSI protected',
        'AE1 - Disabled Medicaid, SSI',
        'AE2 - Disabled Medicaid (SSI)',
        'AE8 - Disabled Medicaid, 1619(b) ',
        'AE9 - Disabled Medicaid, Pickle Amendment',
        'AF1 - Disabled Medicaid, Disabled Adult Child age 18 or older',
        'AF2 - Disabled Medicaid (Widow(er)) (entitled to Medicare)  ',
        'AG1 - Blind Medicaid, Disabled Adult Child age 18 or older',
        'AH2 - Aged Medicaid (Widow(er))',
        'AH3 - Disabled Medicaid, Widow(er) age 60 through 64 ',
        'AH4 - Disabled Medicaid, Disabled Widow(er) age 50 through 59',
        'AJ1 - Disabled Medicaid - Child (K Kids) ',
        'AK1 - IV-E Kinship Guardianship Medicaid',
        'AUT - Autism Waiver',
        'B12 - Nursing home Medicaid, Aged ',
        'B13 - Aged Medicaid, income less than or equal to 100% FPL',
        'B14 - Nursing Home Medicaid, Pregnant Woman income less than or equal to 300% FBR',
        'B21 - Nursing Home Medicaid - Blind ',
        'B22 - Nursing Home Medicaid, Blind',
        'B32 - Nursing Home Medicaid, Disabled ',
        'B33 - Disabled Medicaid, income less than or equal to 100% FPL',
        'B35 - Disabled Medicaid, MWI, Assets less than MWI criteria',
        'B36 - Disabled Medicaid, MWI, assets less than resource limit for 100% FPL',
        'B37 - Disabled Medicaid, MWI, assets over resource limit for 100% FPL and less than MWI limit',
        'B39 - Breast and Cervical Cancer Medicaid',
        'B4 - Aged Medicaid, not on SSI',
        'B5 - Blind Medicaid, not on SSI',
        'B6 - Disabled Medicaid, not on SSI',
        'B71 - Family Medicaid - Adult (AFDC)',
        'B72 - Child, not AFDC financial, not institutionalized',
        'B74 - Child, not AFDC financial, not institutionalized',
        'B81 - Child, not AFDC financial, not institutionalized',
        'B91 - Subsidized adoption Medicaid, non-IVE ',
        'BCF - Foster Care Medicaid (non-IVE)',
        'BDC - Foster Care Medicaid-non-IVE, disabled, income less than or equal to 100% FPL',
        'BDW - Foster Care Medicaid, non-IVE child, disabled, MWI',
        'BYB - Baby Your Baby, Presumptive Pregnant Woman',
        'C12 - Nursing Home Medicaid, Aged, income over 300% FBR',
        'C13 - Nursing Home Medicaid, Child, income over 300% FBR',
        'C14 - Nursing Home Medicaid, Pregnant, income over 300% FBR',
        'C22 - Nursing Home Medicaid, Blind, income over 300% FBR',
        'C32 - Nursing Home Medicaid, Disabled, income over 300% FBR',
        'C43 - Aged Medicaid, spenddown',
        'C53 - Blind Medicaid, non-SSI, spenddown, income > 100% FPL',
        'C63 - Disabled Medicaid, spenddown',
        'C7 - Pregnant Woman Medicaid (Spenddown)',
        'C71 - Family Medicaid, Adult, spenddown $0',
        'C72 - Family Medicaid, Child, spenddown $0',
        'C73 - Family Medicaid, Adult, spenddown',
        'C74 - Family Medicaid, Child, spenddown ',
        'C81 - Family Medicaid, Child, spenddown $0',
        'C82 - Family Medicaid, Child, spenddown',
        'C95 - Nursing Home Medicaid, Aged, ancillary, spenddown',
        'CA5 - Nursing Home Medicaid, Disabled, ancillary, spenddown',
        'CB5 - Nursing Home Medicaid, Blind, ancillary, spenddown',
        'CBF - Foster Care Medicaid, Blind, non-IVE, spenddown',
        'CCF - Foster Care Medicaid, Child, non-IVE foster care',
        'CD1 - Community Supports Waiver, Aged, income over 300% FBR',
        'CD2 - Community Supports Waiver, Blind, income over 300% FBR',
        'CD3 - Community Supports Waiver, Disabled, income over 300% FBR',
        'CD4 - Community Supports Waiver, Child, income over 300% FBR',
        'CD5 - Community Supports Waiver, Adult, income over 300% FBR',
        'CDF - Foster Care Medicaid, Disabled, spenddown > $0',
        'CFC - Foster Care Medicaid, Child or pregnant, spenddown > $0',
        'CI1 - CHIP Plan A',
        'CI2 - CHIP Plan B',
        'CI3 - CHIP Plan C',
        'CI4 - Utah Premium Partnership, Child, Employer sponsored medical, dental',
        'CI5 - Utah Premium Partnership, Child, Employer sponsored medical, CHIP dental',
        'CI6 - Utah Premium Partnership, Child, COBRA medical/ dental, started prior to application',
        'CI7 - Utah Premium Partnership, Child, COBRA medical, started before appl, CHIP dental',
        'CI8 - Utah Premium Partnership, Child, COBRA medical/ dental started after application',
        'CI9 - Utah Premium Partnership, Child, COBRA medical, started after appl, CHIP dental',
        'CIP - CHIP Presumptive',
        'CT2 - Tech Dependent Waiver, Blind, income over 300% FBR',
        'CT3 - Tech Dependent Waiver, Disabled, income over 300% FBR',
        'CT4 - Tech Dependent Waiver, Child, income over 300% FBR',
        'CWA - Aging waiver, income over 300% FBR',
        'D1 - Custody Medical Care',
        'D2 - Juvenile Justice System',
        'D3 - Medical Review Board',
        'D4 - General Assistance State Supplemental Payment',
        'E - Migrant Medical',
        'EV - Katrina Evacuee',
        'EVQ - Katrina Evacuee - QMB',
        'I18 - Foster care Independent Living Medicaid, 18 through 20, emergency only',
        'IA1 - Aged Medicaid - Emergency (Income < SSI rate)',
        'IA2 - Aged Medicaid, emergency only, spenddown',
        'IA3 - Aged Medicaid, emergency only, income less than or equal to 100% FPL',
        'IA9 - Qualified Medicare Beneficiary, Aged',
        'IB1 - Blind Medicaid - Emergency ',
        'IB2 - Blind Medicaid, emergency only, may or may not have a spenddown',
        'IB9 - Qualified Medicare Beneficiary, Blind',
        'IC1 - Child Medicaid - Emergency ',
        'IC2 - Child, emergency only, spenddown',
        'ICF - Foster care Medicaid, non-IVE, emergency only',
        'ID1 - Disabled Medicaid - Emergency (Income < SSI rate) ',
        'ID2 - Disabled Medicaid, emergency only, spenddown',
        'ID3 - Disabled Medicaid, emergency only, income less than or equal to 100% FPL',
        'ID4 - Disabled Medicaid, MWI, emergency only, ',
        'ID5 - Breast and cervical cancer Medicaid, emergency only',
        'ID9 - Qualified Medicare Beneficiary, Disabled',
        'IF1 - Family Medicaid, Adult, emergency only',
        'IF2 - Family Medicaid, Adult, emergency only, spenddown',
        'IF5 - Family Medicaid - Emergency (Child)',
        'IF6 - Family Medicaid, Child, emergency only, spenddown',
        'IF7 - Pregnant woman Medicaid, emergency only, spenddown',
        'IF8 - Child Medicaid, age 0 through 5',
        'IF9 - Pregnant Woman Medicaid, emergency only',
        'IFP - Pregnant Woman Medicaid - Emergency (High Risk)',
        'IO9 - Disabled, QMB only, Medicare entitled under Railroad or government employment',
        'IP1 - Child Medicaid, age 6 through 18, emergency only',
        'MCC - Medically Complex Waiver, Child',
        'MP1 - Child Medicaid - Presumptive, ages 0 through 5',
        'MP2 - Child Medicaid - Presumptive, ages 6 through 18',
        'P19 - Former Foster Care-Presumptive Eligibility, 18 through 25',
        'P82 - Pregnant Woman Medicaid (High Risk)',
        'PC1 - Primary Care Network, adult with dependent children',
        'PC2 - Primary Care Network, adult without dependent children',
        'PC3 - Utah Premium Partnership, Adult with dependent child',
        'PC4 - Utah Premium Partnership, Adult w/o dependent child',
        'PC5 - Utah Premium Partnership, Adult w/dependent child, COBRA started before appl',
        'PC6 - Utah Premium Partnership, Adult w/o dependent child, COBRA started before appl',
        'PC7 - Utah Premium Partnership, Adult w/dependent child, COBRA started after appl.',
        'PC8 - Utah Premium Partnership, Adult w/o dependent child, COBRA started after application',
        'PCR - Parent Caretaker Relative Medicaid, Presumptive',
        'PFM - Family Medicaid - Pregnant',
        'Q12 - Nursing Home Medicaid and QMB, Aged',
        'Q13 - Aged Medicaid and QMB, income less than or equal to 100% FPL',
        'Q22 - Nursing Home Medicaid and QMB, Blind',
        'Q32 - Disabled Medicaid and QMB, institutional, not SSI, income less than or equal to 100% FPL',
        'Q33 - Disabled Medicaid and QMB, income less than or equal to 100% FPL',
        'Q35 - Disabled Medicaid, MWI and QMB',
        'Q37 - Family Medicaid, PCR and QMB',
        'Q42 - Adult, Medicaid, Chronically Homeless Individuals & QMB',
        'Q43 - Adult Medicaid, Justice Involved Individuals  QMB',
        'Q44 - Adult Medicaid, Individuals Needing Substance Abuse or Mental Health Treatment & QMB',
        'Q51 - Family Medicaid and QMB, Adult, 4-month spousal support',
        'Q53 - Blind Medicaid and QMB, spenddown $0 if income is > BMS and <100% FPL',
        'Q57 - Family Medicaid and QMB, Adult, 12-month earned income increase',
        'Q71 - Family Medicaid and QMB - Adult',
        'Q73 - Family Medicaid and QMB, Adult, spenddown',
        'Q82 - Pregnant Woman Medicaid and QMB',
        'Q94 - Nursing Home Medicaid and QMB, Aged SSI or Protected group',
        'Q95 - Aged Medicaid, ancillary only, QMB, institutional or waiver, income less than or equal to 300% FBR',
        'QA1 - Family Medicaid and QMB - Adult',
        'QA2 - Family Medicaid and QMB - Adult ',
        'QA4 - Nursing Home Medicaid and QMB, Blind, SSI and Protected groups',
        'QA5 - Nursing Home Medicaid and QMB, Blind, ancillary only',
        'QA6 - Family Medicaid and QMB - Adult (Parent/Caretaker Relative)',
        'QB1 - Acquired Brain Injury Waiver and QMB, Aged',
        'QB2 - Acquired Brain Injury Waiver and QMB, Disabled',
        'QB3 - Acquired Brain Injury Waiver and QMB, Blind',
        'QB4 - Aged, spenddown $0',
        'QB5 - Blind, spenddown $0 and QMB',
        'QB6 - Disabled, spenddown $0',
        'QC1 - Adult, spenddown $0',
        'QC3 - Aged Medicaid and QMB, SSI',
        'QC8 - Aged Medicaid and QMB, 1619(b)',
        'QC9 - Aged Medicaid and QMB, Pickle Amendment',
        'QCC - Medically Complex child waiver and QMB, Child ',
        'QD1 - Blind Medicaid and QMB, SSI',
        'QD2 - Community Supports Waiver and QMB, Disabled ',
        'QD3 - Community Supports waiver and QMB, Blind',
        'QD4 - Community Supports waiver and QMB - Child',
        'QD6 - Community Supports Waiver and QMB, Aged',
        'QD8 - Blind Medicaid and QMB, 1619(b) ',
        'QD9 - Blind Medicaid and QMB, Pickle Amendment',
        'QE1 - Disabled Medicaid and QMB, SSI ',
        'QE2 - Family Medicaid and QMB - Adult (4 Month Extension)',
        'QE3 - Family Medicaid and QMB - Adult ( 9 or 12 Month Extension)',
        'QE8 - Disabled Medicaid and QMB, 1619(b) ',
        'QE9 - Disabled Medicaid and QMB, Pickle Amendment',
        'QF1 - Disabled Medicaid and QMB, Disabled Adult Child age 18 and older',
        'QF2 - Disabled Medicaid and QMB [Widow(er)]',
        'QG1 - Blind Medicaid and QMB, Disabled Adult Child age 18 and older',
        'QH2 - Aged Medicaid and QMB [Widow(er)]',
        'QN1 - New Choices Waiver and QMB,  Aged, SSI or Protected groups',
        'QN2 - New Choices Waiver and QMB, Aged, income less than or equal to 100% FPL',
        'QN5 - New Choices Waiver and QMB, Disabled, SSI or Protected groups ',
        'QN6 - New Choices Waiver and QMB, Disabled, with income less than or equal to 100% FPL',
        'QP1 - Physical Disabilities waiver and QMB, Aged, income less than or equal to 100% FPL',
        'QP2 - Physical Disabilities waiver and QMB, Blind, income less than or equal to 100% FPL',
        'QP3 - Physical Disabilities waiver and QMB, Disabled, income less than or equal to 100% FPL',
        'QQ4 - Nursing Home Medicaid and QMB, Disabled, SSI ',
        'QQ5 - Nursing Home Medicaid and QMB, Disabled, ancillary only',
        'QT2 - Tech Dependent Waiver and QMB, Disabled ',
        'QT3 - Tech Dependent Waiver and QMB, Blind ',
        'QT4 - Child Medicaid, Technology waiver,  and QMB with income less than or equal to 100% FPL',
        'QWA - Aging Waiver Medicaid and QMB',
        'RM1 - Refugee Medical, Adult',
        'RM2 - Refugee Medical, Child',
        'TB - Tuberculosis Medicaid',
        'TD1 - Tech Dependent Waiver, Aged',
        'TD2 - Tech Dependent Waiver, Disabled',
        'TD3 - Tech Dependent Waiver, Blind',
        'TD4 - Tech Dependent Waiver, Child',
        'TD5 - Tech Dependent Waiver, Adult',
        'WAI -  Aging Waiver',
        'WB1 - Acquired Brain Injury Waiver, Aged',
        'WB2 - Acquired Brain Injury Waiver, Disabled',
        'WB3 - Acquired Brain Injury Waiver, Blind',
        'WB4 - Acquired Brain Injury Waiver, Adult',
        'WB5 - Acquired Brain Injury waiver, Aged, income > 300% FBR',
        'WB6 - Acquired Brain Injury waiver, Disabled, income > 300% FBR',
        'WB7 - Acquired Brain Injury waiver, Blind, income > 300% FBR',
        'WD1 - Community Supports Waiver, Aged, income less than or equal to 300% FBR',
        'WD2 - Community Supports Waiver, Disabled, income less than or equal to 300% FBR',
        'WD3 - Community Supports Waiver, Blind, income less than or equal to 300% FBR',
        'WD4 - Community Supports Waiver, Child, income less than or equal to 300% FBR',
        'WD5 - Community Supports Waiver, Adult, income less than or equal to 300% FBR',
        'WN1 - New Choices Waiver, Aged, SSI or Protected groups',
        'WN2 - New Choices Waiver, Aged, income less than or equal to 100% FPL',
        'WN3 - New Choices waiver, Aged, income > 300% FBR',
        'WN4 - New Choices Waiver, Aged, income less than or equal to 300% FBR',
        'WN5 - New Choices Waiver - Disabled, SSI or Protected groups',
        'WN6 - New Choices Waiver, Disabled, income less than or equal to 100% FPL',
        'WN7 - New Choices Waiver, Disabled, MWI',
        'WN8 - New Choices Waiver, Disabled, income > 300% FBR',
        'WN9 - New Choices Waiver, Disabled, income less than or equal to 300% FBR',
        'WP1 -  Physical Disabilities waiver, Aged',
        'WP2 - Physical Disabilities Waiver, Blind',
        'WP3 - Physical Disabilities Waiver, Disabled',
        'WP4 -  Physical Disabilities waiver, Aged, income > 300% FBR',
        'WP5 - Physical Disabilities Waiver, Blind, income > 300% FBR',
        'WP6 - Physical Disabilities Waiver, Disabled, income > 300% FBR',
        'CWD - Aging waiver, Disabled, income over 300% FBR',
        'QWD - Aging Waiver, Disabled, Medicaid and QMB',
        'WAD - Aging Waiver, Disabled',
        'E01 - Adult Expansion, age 21 to 64, adult w/ dependent children',
        'E02 - Adult Expansion, age 19 to 20, adult w/ dependent',
        'E03 - Adult Expansion, age 21 to 64, 100%, adult w/ dependent children',
        'E04 - Adult Expansion, age 19 to 20, 100%, adult w/ dependent children',
        'E07 - Adult Expansion, age 21 to 64, 100%, adult w/o dependent children',
        'E08 - Adult Expansion, age 19 to 20, 100%, adult w/o dependent children',
        'EP1 - Adult Expansion, age 21 to 64, 133%, Presumptive, adult w/ dependent children',
        'EP2 - Adult Expansion, age 19 to 20, 133%, Presumptive, adult w/ dependent children',
        'EP3 - Adult Expansion, age 21 to 64, 133%, Presumptive, adult w/o dependent children',
        'EP4 - Adult Expansion, age 19 to 20, 133%, Presumptive, adult w/o dependent children',
        'EE1 - Adult Expansion, age 19 to 64, adult w/ dependent children, emergency only',
        'EE2 - Adult Expansion, age 19 to 64, 133%, adult w/ dependent children, emergency only',
        'EE3 - Adult Expansion, age 19 to 64, 133%, adult w/o dependent children, emergency only',
        'E05 - Adult Expansion, age 21 to 64, 133%, adult w/ dependent children',
        'E06 - Adult Expansion, age 19 to 20, 133%, adult w/ dependent children',
        'ES3 - Adult Expansion, age 21 to 64, 100%, ESI, adult w/ dependent children',
        'ES4 - Adult Expansion, age 19 to 20, 100%, ESI, adult w/ dependent children',
        'ES5 - Adult Expansion, age 21 to 64, 133%, ESI, adult w/ dependent children',
        'ES6 - Adult Expansion, age 19 to 20, 133%, ESI, adult w/ dependent children',
        'E09 - Adult Expansion, age 21 to 64, 133%, adult w/o dependent children',
        'E0A - Adult Expansion, age 19 to 20, 133%, adult w/o dependent children',
        'ES7 - Adult Expansion, age 21 to 64, 100%, ESI, adult w/o dependent children',
        'ES8 - Adult Expansion, age 19 to 20, 100%, ESI, adult w/o dependent children',
        'ES9 - Adult Expansion, age 21 to 64, 133%, ESI, adult w/o dependent',
        'ESA - Adult Expansion, age 19 to 20, 133%, ESI, adult w/o dependent children',
        'EFA - Adult Expansion, age 21 to 64, 100%, Medically Frail, adult w/ dependent children',
        'EFB - Adult Expansion, age 19 to 20, 100%, Medically Frail, adult w/ dependent children',
        'EFC - Adult Expansion, age 21 to 64, 133%, Medically Frail, adult w/ dependent children',
        'EFD - Adult Expansion, age 19 to 20, 133%, Medically Frail, adult w/ dependent children',
        'EFE - Adult Expansion, age 21 to 64, 100%, Medically Frail, adult w/ dependent children, Non-Trad',
        'EFF - Adult Expansion, age 19 to 20, 100%, Medically Frail, adult w/ dependent children, Non-Trad',
        'EFG - Adult Expansion, age 21 to 64, 133%, Medically Frail, adult w/ dependent children, Non-Trad',
        'EFH - Adult Expansion, age 19 to 20, 133%, Medically Frail, adult w/ dependent children, Non-Trad',
        'COV - Uninsured COVID-19 diagnostic testing',
        'WC0 - Community Transitions Waiver, Aged, SSI or Protected Groups',
        'WC2 - Community Transitions Waiver, Aged, income less than or equal to 100% FPL',
        'WC3 - Community Transitions Waiver, Aged, income over 300% FBR',
        'WC4 - Community Transitions Waiver, Aged, income less than or equal to 300% FBR',
        'WC5 - Community Transitions Waiver, Disabled, SSI or Protected Groups',
        'WC6 - Community Transitions waiver, Disabled, income less than or equal to 100% FPL',
        'WC7 - Community Transitions Waiver, Disabled, MWI',
        'WC8 - Community Transitions waiver, Blind or Disabled, income over 300% FBR',
        'WCA - Community Transitions waiver, Blind or Disabled, income less than or equal to 300% FBR',
        'QC0 - Community Transitions Waiver and QMB, Aged, SSI or Protected groups',
        'QC2 - Community Transitions Waiver and QMB, Aged, income less than or equal to 100% FPL',
        'QC4 - Community Transitions Waiver and QMB, Aged, special income group',
        'QC5 - Community Transitions Waiver and QMB, Disabled, SSI or Protected groups',
        'QC6 - Community Transitions Waiver and QMB, Disabled, with income less than or equal to 100% FPL',
        'QCA - Community Transitions Waiver and QMB, Blind or Disabled, special income group.',
        'EN1 - Nursing Home, age 21 to 64, adults without dependent children',
        'EN2 - Nursing Home, age 19 to 20, adults without dependent children',
        'EN3 - Nursing Home, age 21 to 64, adults without dependent children, ancillary',
        'EN4 - Nursing Home, age 19 to 20, adults without dependent children, ancillary',
        'EN5 - Nursing Home, age 21 to 64, adults with dependent children',
        'EN6 - Nursing Home, age 19 to 20, adults with dependent children',
        'EN7 - Nursing Home, age 21 to 64, adults with dependent children, ancillary',
        'EN8 - Nursing Home, age 19 to 20, adults with dependent children, ancillary',
        'LS1 - Limited Supports Waiver, Aged, SSI or Protected Groups',
        'LS2 - Limited Supports Waiver, Aged, income less than or equal to 100% FPL',
        'LS3 - Limited Supports Waiver, Aged, income over 300% FBR',
        'LS4 - Limited Supports Waiver, Aged, income less than or equal to 300% FBR',
        'LS5 - Limited Supports Waiver, Blind or Disabled, SSI or Protected Groups',
        'LS6 - Limited Supports Waiver, Disabled, income less than or equal to 100% FPL',
        'LS7 - Limited Supports Waiver, Disabled, MWI',
        'LS8 - Limited Supports Waiver, Blind or Disabled, income over 300% FBR',
        'LS9 - Limited Supports Waiver, Blind or Disabled, income less than or equal to 300% FBR',
        'QS1 - Limited Supports Waiver and QMB, Aged, SSI or Protected groups',
        'QS2 - Limited Supports Waiver and QMB, Aged, income less than or equal to 100% FPL',
        'QS4 - Limited Supports Waiver and QMB, Aged, special income group',
        'QS5 - Limited Supports Waiver and QMB, Blind or Disabled, SSI or Protected groups',
        'QS6 - Limited Supports Waiver and QMB, Disabled, with income less than or equal to 100% FPL',
        'QS9 - Limited Supports Waiver and QMB, Blind or Disabled, special income group',
        'C76 - Family Medicaid, Adult, spenddown',
        'II9 - Qualified Medicare Beneficiary, Medicare Part B-ID',
        'IN9 - Qualified Medicare Beneficiary, Medicare not aged or disabled',
        'D5 - Juvenile Justice System Medicaid',
        'D6 - Juvenile Justice System CHIP',
        'ESB - Adult Expansion, age 21 to 64, 133%, ESI, adult w/ dependent children',
        'PCS - Parent Caretaker Relative Medicaid, Presumptive',
        'Q58 - Family Medicaid and QMB, Adult, 4-month spousal support',
        'Q59 - Family Medicaid and QMB, Adult, 12-month earned income increase',
        'Q76 - Family Medicaid and QMB, Adult, spenddown',
        'QA8 - Family Medicaid and QMB - Adult (Parent/Caretaker Relative)',
        'CHP - State CHIP',
        'A38 - Family Medicaid, Adult Parent/ Caretaker Relative',
        'A58 - Family Medicaid, Adult, 4-month spousal support increase',
        'A59 - Family Medicaid, Adult, 12-month transitional earned income increase',
        'E0B - Adult Expansion, age 21 to 64, 133%, adult w/ dependent children',
        'EP5 - Adult Expansion, age 21 to 64, 133%, Presumptive, adult w/ dependent children',
    ],
    values: [
        'A1',
        'A18',
        'A19',
        'A1A',
        'A21',
        'A22',
        'A23',
        'A31',
        'A32',
        'A35',
        'A36',
        'A37',
        'A4',
        'A42',
        'A43',
        'A44',
        'A5',
        'A51',
        'A52',
        'A55',
        'A57',
        'A61',
        'A62',
        'A63',
        'A64',
        'A65',
        'A66',
        'A67',
        'A68',
        'A69',
        'A7',
        'A8',
        'A80',
        'A81',
        'A82',
        'A83',
        'A84',
        'A94',
        'A95',
        'AA4',
        'AA5',
        'AB4',
        'AB5',
        'ABF',
        'AC3',
        'AC4',
        'AC8',
        'AC9',
        'ACF',
        'AD1',
        'AD2',
        'AD8',
        'AD9',
        'ADF',
        'AE1',
        'AE2',
        'AE8',
        'AE9',
        'AF1',
        'AF2',
        'AG1',
        'AH2',
        'AH3',
        'AH4',
        'AJ1',
        'AK1',
        'AUT',
        'B12',
        'B13',
        'B14',
        'B21',
        'B22',
        'B32',
        'B33',
        'B35',
        'B36',
        'B37',
        'B39',
        'B4',
        'B5',
        'B6',
        'B71',
        'B72',
        'B74',
        'B81',
        'B91',
        'BCF',
        'BDC',
        'BDW',
        'BYB',
        'C12',
        'C13',
        'C14',
        'C22',
        'C32',
        'C43',
        'C53',
        'C63',
        'C7',
        'C71',
        'C72',
        'C73',
        'C74',
        'C81',
        'C82',
        'C95',
        'CA5',
        'CB5',
        'CBF',
        'CCF',
        'CD1',
        'CD2',
        'CD3',
        'CD4',
        'CD5',
        'CDF',
        'CFC',
        'CI1',
        'CI2',
        'CI3',
        'CI4',
        'CI5',
        'CI6',
        'CI7',
        'CI8',
        'CI9',
        'CIP',
        'CT2',
        'CT3',
        'CT4',
        'CWA',
        'D1',
        'D2',
        'D3',
        'D4',
        'E',
        'EV',
        'EVQ',
        'I18',
        'IA1',
        'IA2',
        'IA3',
        'IA9',
        'IB1',
        'IB2',
        'IB9',
        'IC1',
        'IC2',
        'ICF',
        'ID1',
        'ID2',
        'ID3',
        'ID4',
        'ID5',
        'ID9',
        'IF1',
        'IF2',
        'IF5',
        'IF6',
        'IF7',
        'IF8',
        'IF9',
        'IFP',
        'IO9',
        'IP1',
        'MCC',
        'MP1',
        'MP2',
        'P19',
        'P82',
        'PC1',
        'PC2',
        'PC3',
        'PC4',
        'PC5',
        'PC6',
        'PC7',
        'PC8',
        'PCR',
        'PFM',
        'Q12',
        'Q13',
        'Q22',
        'Q32',
        'Q33',
        'Q35',
        'Q37',
        'Q42',
        'Q43',
        'Q44',
        'Q51',
        'Q53',
        'Q57',
        'Q71',
        'Q73',
        'Q82',
        'Q94',
        'Q95',
        'QA1',
        'QA2',
        'QA4',
        'QA5',
        'QA6',
        'QB1',
        'QB2',
        'QB3',
        'QB4',
        'QB5',
        'QB6',
        'QC1',
        'QC3',
        'QC8',
        'QC9',
        'QCC',
        'QD1',
        'QD2',
        'QD3',
        'QD4',
        'QD6',
        'QD8',
        'QD9',
        'QE1',
        'QE2',
        'QE3',
        'QE8',
        'QE9',
        'QF1',
        'QF2',
        'QG1',
        'QH2',
        'QN1',
        'QN2',
        'QN5',
        'QN6',
        'QP1',
        'QP2',
        'QP3',
        'QQ4',
        'QQ5',
        'QT2',
        'QT3',
        'QT4',
        'QWA',
        'RM1',
        'RM2',
        'TB',
        'TD1',
        'TD2',
        'TD3',
        'TD4',
        'TD5',
        'WAI',
        'WB1',
        'WB2',
        'WB3',
        'WB4',
        'WB5',
        'WB6',
        'WB7',
        'WD1',
        'WD2',
        'WD3',
        'WD4',
        'WD5',
        'WN1',
        'WN2',
        'WN3',
        'WN4',
        'WN5',
        'WN6',
        'WN7',
        'WN8',
        'WN9',
        'WP1',
        'WP2',
        'WP3',
        'WP4',
        'WP5',
        'WP6',
        'CWD',
        'QWD',
        'WAD',
        'E01',
        'E02',
        'E03',
        'E04',
        'E07',
        'E08',
        'EP1',
        'EP2',
        'EP3',
        'EP4',
        'EE1',
        'EE2',
        'EE3',
        'E05',
        'E06',
        'ES3',
        'ES4',
        'ES5',
        'ES6',
        'E09',
        'E0A',
        'ES7',
        'ES8',
        'ES9',
        'ESA',
        'EFA',
        'EFB',
        'EFC',
        'EFD',
        'EFE',
        'EFF',
        'EFG',
        'EFH',
        'COV',
        'WC0',
        'WC2',
        'WC3',
        'WC4',
        'WC5',
        'WC6',
        'WC7',
        'WC8',
        'WCA',
        'QC0',
        'QC2',
        'QC4',
        'QC5',
        'QC6',
        'QCA',
        'EN1',
        'EN2',
        'EN3',
        'EN4',
        'EN5',
        'EN6',
        'EN7',
        'EN8',
        'LS1',
        'LS2',
        'LS3',
        'LS4',
        'LS5',
        'LS6',
        'LS7',
        'LS8',
        'LS9',
        'QS1',
        'QS2',
        'QS4',
        'QS5',
        'QS6',
        'QS9',
        'C76',
        'II9',
        'IN9',
        'D5',
        'D6',
        'ESB',
        'PCS',
        'Q58',
        'Q59',
        'Q76',
        'QA8',
        'CHP',
        'A38',
        'A58',
        'A59',
        'E0B',
        'EP5',
    ]
}

const countyOptions = {
    labels: [
        'BEAVER',
        'BOX ELDER',
        'CACHE',
        'CARBON',
        'DAGGETT',
        'DAVIS',
        'DUCHESNE',
        'EMERY',
        'GARFIELD',
        'GRAND',
        'IRON',
        'JUAB',
        'KANE',
        'MILLARD',
        'MORGAN',
        'PIUTE',
        'RICH',
        'SALT LAKE',
        'SAN JUAN',
        'SANPETE',
        'SEVIER',
        'SUMMIT',
        'TOOELE',
        'UINTAH',
        'UTAH',
        'WASATCH',
        'WASHINGTON',
        'WAYNE',
        'WEBER',
        'OUT OF STATE',],
    values: [
        'CT100',
        'CT101',
        'CT102',
        'CT103',
        'CT104',
        'CT105',
        'CT106',
        'CT107',
        'CT108',
        'CT109',
        'CT110',
        'CT111',
        'CT112',
        'CT113',
        'CT114',
        'CT115',
        'CT116',
        'CT117',
        'CT118',
        'CT119',
        'CT120',
        'CT121',
        'CT122',
        'CT123',
        'CT124',
        'CT125',
        'CT126',
        'CT127',
        'CT128',
        'CT129',
    ]
}

const benefitSubTypeOptions = {
    labels: [
        '168: SLMB - No Benefit',
        '172: SLMB - No Benefit',
        '152: QI - No Benefit',
        '153: Qualified Disabled Working Individual',
        // '174: SLMB - No Benefit',
        // '176: SLMB - No Benefit',
        // '154: QI - No Benefit',
    ],
    values: [
        '168',
        '172',
        '152',
        '153',
        // '174',
        // '176',
        // '154',
    ]
}

const incarcerationStatusOptions = {
    labels: [
        'RST1 - Active',
        'RST2 - Inactive'
    ],
    values: [
        'RST1',
        'RST2'
    ]
}

const denialClosureOptions = {
    labels: [
        'CC2 - Not Eligible',
        'CC4 - Certification Grace Period Exceeded',
        'CC6 - Failure to pay premiums',
        'CCR102 - Customer Moved Out of State',
        'CCR103 - Customer Request',
        'CCR104 - Customer Withdrew Application',
        'CCR105 - Failed to provide info',
        'CCR108 - UPP Insurance Not Verified',
        'CCR110 - Review not submitted',
        'CCR111 - Unable to Locate',
        'CCR216 - Receiving in Another State',
        'CCR321 - Administrative',
        'CCR322 - Incomplete Claim (Overpayment & Investigations)',
        'CCR323 - Prenatal Asset Copayment not paid',
        'CCR324 - Fee Not Paid - PCN',
        'CCR325 - Spenddown Exceeds Need or Not Paid',
        'CCR326 - Auto denial after thirty days of application',
        'CCR327 - MWI Premium Not Paid',
        'CCR401 - Customer Reported',
        'CCR500 - Program created at Cascade',
        'CCR501 - Program reverted to "open"/All members covered',
        'CCR900 - DWS Decision',
        'CCR901 - Over Income limit',
        'CCR902 - Fails citizenship',
        'CCR903 - Fails residency',
        'CCR904 - Currently has health insurance',
        'CCR905 - Incomplete application',
        'CCR906 - Already receiving Medicaid or CHIP',
        'CCR907 - Issued Presumptive in the last 6 months',
        'CCR908 - Time Limit Expired',
        'CCR909 - No Deprivation',
        'CCR910 - No Available PE Program',
        'CCR911 - Medical Denial in the Past 30 Days',
        'CCR912 - Not Enought Information to Determine PE',
        'CCR913 - Already Received PE for the Current Pregnancy',
        'CCR915 - No Open Enrollment',
        'CCR916 - Denial - Adult Medicaid Expansion',
        'CCR1203 - CHIP Insufficient Funds',
        'CCR1212 - Failure to pay premiums',
        'CCR1215 - Failure to pay premiums',
        'CCR1315 - PCN Insufficient Funds',
        'CCR2000 - Fails 180 days of Utah Residency',
    ],
    values: [
        'CC2',
        'CC4',
        'CC6',
        'CCR102',
        'CCR103',
        'CCR104',
        'CCR105',
        'CCR108',
        'CCR110',
        'CCR111',
        'CCR216',
        'CCR321',
        'CCR322',
        'CCR323',
        'CCR324',
        'CCR325',
        'CCR326',
        'CCR327',
        'CCR401',
        'CCR500',
        'CCR501',
        'CCR900',
        'CCR901',
        'CCR902',
        'CCR903',
        'CCR904',
        'CCR905',
        'CCR906',
        'CCR907',
        'CCR908',
        'CCR909',
        'CCR910',
        'CCR911',
        'CCR912',
        'CCR913',
        'CCR915',
        'CCR916 ',
        'CCR1203',
        'CCR1212',
        'CCR1215',
        'CCR1315',
        'CCR2000',
    ]
}

const districtOfficeOptions = {
    labels: [
        'BMC-Contract\'s Unit - 913',
        'BMC-HPR Unit 1 - 914',
        'BMC-HPR Unit 2 - 915',
        'HCF-Long Term Care Unit - 920',
        'Bureau of Eligibility Services - 930',
        'Bureau of Medicaid Operations - 940',
        'Bureau of Financial Services - 950',
        'BFS-Budget & Forecasting Unit - 951',
        'BFS-Audit Unit - 952',
        'Bureau of Coverage & Reimbursement - 960',
        'BCR-Program Integrity & Utilization Mgmt - 961',
        'BCR-Institutional Policy & Transplants - 962',
        'BCR-Non-institutional Policy - 963',
        'BCR-Reimbursement Policy - 964',
        'HCF-Director\'s Office - 902',
        'HCF-ITU-Info. Technology Unit - 903',
        'DHS - Jackson Office - DCFS - SCJ',
        'DCFS Richfield - SSR',
        'Workforce Services N Region Roy Office - WHR',
        'WS-Woods Cross - South Davis - WNX',
        'WS- Fam Office (inactive) - WCC',
        'Unknown - UKN',
        'WS-Roy - WNR',
        'Bureau of Medicaid Operations - FC - BMO',
        'DHS-Payson-DCFS - SMO',
        'DCFS-Admin Office (inactive) - SAO',
        'DWS  Administration - WAO',
        'WS-Central ESC - WCE',
        'WS-Investigations - WCI',
        'WS-Richfield South - WWI',
        'WS-Central-West Valley City Office - WCW',
        'DHS - Independent Living Pgm - SCK',
        'DH-Dixie Reg Med Center-BES - HWH',
        'WS-Moab - WEM',
        'DH-Telecommuter/Gunnison - HW1',
        'DH-Layton (Inactive DRO) - HNP',
        'DH-West Valley Ellis Shipp Clinic-BES - HOE',
        'DH-Telecommuter/Moroni - HW2',
        'DH-Delta Office - HWD',
        'DH-Monument Valley Health-BES - HEY',
        'DH-Granite School District - HO7',
        'DH-Heber City Office-BES - HMH',
        'DH-Midvale Copperview Clinic-BES - HOV',
        'DH-North Ogden Telecommuter-BES - HNJ',
        'DH-Central Hub Office - HNI',
        'DH-Castledale-BES - HEC',
        'DH-Primary Children\'s Medical Center-BES - HOP',
        'WS-Nephi - WWN',
        'DH-Central Hub Office-BES - HC1',
        'DH-Beaver - HWB',
        'DH-Oquirrh View Clinic-BES - HOO',
        'DH- Magna FACT Office - HO4',
        'DH-Moab Office-BES - HEM',
        'DH-SL Health Clinics of Utah Office - HO5',
        'DH-American Fork Telecommuter-BES - HM3',
        'WS-Tooele - WCT',
        'DH-Pioneer Valley Hospital-BES - HO3',
        'WS-Roosevelt - WER',
        'DH-Cedar City Office-BES - HWC',
        'WS-Logan - WNA',
        'DH-Ogden Northern Region Aging - HNA',
        'DH-Tooele Office-BES - HCT',
        'DH-Montezuma Creek Hlth Clinic - HEZ',
        'WS-Brigham City - WNB',
        'DH-Central Valley Med Center - HWN',
        'DH-Blanding Office -BES - HEB',
        'DH-Vernal Office-BES - HEV',
        'DH-Brigham City Office-BES - HNB',
        'DH-Logan Office-BES - HNL',
        'WS-Manti - WWM',
        'DH-Richfield-BES - HWR',
        'DH-SL County Govt Center-BES - HCX',
        'DH-Holladay DSPD Office-BES - HO1',
        'DH-Roosevelt Office-BES - HER',
        'DH-Price Office-BES - HEP',
        'WS-Vernal Office - WEV',
        'WS-Salt Lake City-WSC - WSC',
        'WS-Cedar City - WWC',
        'WS-Salt Lake City-WSA - WSA',
        'DH-Layton Office/Davis County - HND',
        'WS-Salt Lake City-WSB - WSB',
        'DH-West Jordan Office-BES - HCV',
        'WS-Ogden South - WND',
        'DH-St. George Office-BES - HWS',
        'WS-Richfield Office - WWR',
        'DH-Central Hub Office-Mountain America - HCH',
        'WS-Logan Office - WNL',
        'WS-St. George - WWS',
        'WS-Central Elig. Service Center-WC4 - WC4',
        'WS-Central Elig. Service Center-WC5 - WC5',
        'WS-Central Elig. Service Center-WC8 - WC8',
        'WS-Central Elig. Service Center-WC6 - WC6',
        'WS-Central Elig. Service Center-WC2 - WC2',
        'WS-Central Elig. Service Center-WC3 - WC3',
        'WS-Central Elig. Service Center-WC7 - WC7',
        'WS-Blanding - WEB',
        'DH-Manti Office-BES - HWM',
        'DH-Mountainlands Clinic-BES - HMM',
        'Obsolete Code - C P - C P',
        'Obsolete Code - CC - CC',
        'DOH - Cannon Building - H00',
        'Obsolete Code E C - E C',
        'Obsolete Code E O - E O',
        'Obsolete Code E P - E P',
        'Obsolete Code E V - E V',
        'TO BE DETERMINED LATER HCP - HCP',
        'DH-Davis Hospital and Medical Cntr - HNH',
        'DH-Fillmore Community Medical Clinic - HWF',
        'TO BE DETERMINED LATER HWG - HWG',
        'WS-Junction - WWJ',
        'DH-Family Health Services-BES - HOF',
        'DH-Panguitch Hospital-BES - HWP',
        'DH-Cedar City Valley View Med Center - HWV',
        'DH-LDS Hospital - HOT',
        'DH-Park City Office-BES - HMC',
        'DHS-Ogden-DCFS - SNO',
        'DH-Southeast Public Health Center - HOL',
        'DH-Central Hub Office - BES - HC2',
        'DH-South Main Comm Hlth Center-BES - HOS',
        'DHS-Ogden-DYC - SNC',
        'DH-University of Utah Med Center-BES - HOU',
        'DH- Roosevelt Office - HEF',
        'DH-McKay Dee Hospital-BES - HNM',
        'DHS-Holladay Office-DCFS - SCH',
        'DH-Primary Children\'s Med Center-BES - HOQ',
        'DH-Sanpete Valley Hospital-BES - HWE',
        'DH-Davis County Health Dept (inactive) - HNF',
        'DH-Kaysville Telecommuter-BES - HNN',
        'DH-Downtown Office-BES (inactive) - HCD',
        'WS-Downtown (Expo) W - WCD',
        'DH-Central Hub Office 2-BES - HCR',
        'WS-Metro - WCR',
        'DH-Midvale Office-BES - HCM',
        'WS-Midvale - WCM',
        'DH-South County Office-BES - HCS',
        'WS-Taylorsville South County W - WCS',
        'DH-Ogden Office-BES - HNO',
        'WS-Ogden North - WNO',
        'WS-Clearfield - WNC',
        'DH-Provo Office-BES - HMP',
        'WS-Provo W - WMP',
        'DH-Payson Office-BES - HMO',
        'WS-Payson W - WMO',
        'DH-American Fork Office-BES - HMA',
        'WS-American Fork W - WMA',
        'WS-Price - WEP',
        'Department of Health - HAO',
        'WS-Central Elig. Service Center-WC1 - WC1',
        'Obsolete Code E M - E M',
        'DH-Ogden Community Outreach Worker-BES - HN1',
        'DH-Sunset Office-BES (inactive) - HNS',
        'Obsolete Code N O - N O',
        'Obsolete Code W P - W P',
        'DH-Pioneer Valley Hospital - HO8',
        'Obsolete Code - C C - C C',
        'Obsolete Code - C T - C T',
        'WS-Park City - WMY',
        'Obsolete Code E R - E R',
        'WS-Kanab - WWK',
        'DH-Ut Valley Reg Med Center-BES - HMU',
        'WS-Taylorsville - WCV',
        'DHS-Castledale-DCFS - SEC',
        'DH-University of Utah Medical Center-BES - HOR',
        'DHS-Clearfield-DCFS - SNY',
        'WS-Central Elig. Service Center-WC9 - WC9',
        'DH-Central Office (inactive) - HCC',
        'WS-Monticello - WEO',
        'WS-Beaver - WWB',
        'DH-Salt Lake Reg Med Center-BES - HOH',
        'DHS-Roosevelt-DCFS - SER',
        'WS-Panguitch - WWP',
        'DHS-Provo-DCFS - SMP',
        'DH-Ogden Midtown Comm Hlth Center-BES - HNC',
        'DH-Northwest Clinic-BES - HON',
        'DHS-Cottonwood Office - SCN',
        'WS-Provo North - WMV',
        'DHS-Orem-DYC - SMS',
        'DHS-Cedar City-DCFS - SSW',
        'DHS-Heber-DCFS - SMH',
        'WS-Heber City - WMH',
        'DH-St. Mark\'s Hospital - HOM',
        'DHS-Salt Lake City-DYC - SCY',
        'DH-Central City Clinic-BES - HOC',
        'WS-Castledale - WEC',
        'DHS-Central Office-DCFS - SCC',
        'DHS-South State Office - SCS',
        'DH-Ogden Reg Med Center-BES - HNR',
        'DH-Layton Nursing Homes - HNE',
        'DH-Northern Region - Logan Nursing Home - HNZ',
        'Bureau of Managed Health Care New - MHC',
        'Local Health Dept - LHD',
        'Foster Care - FC',
        'Youth Corrections - YC',
        'Subsidized Adoption - SA',
        'DH-Outreach-Valley Mental Health - HOD',
        'Wasatch County Health Department - WAS',
        'DHS-Juvenile Justice Salt Lake - SCX',
        'DH-Jordan School District - Outreach - HO9',
        'DWS - Northern Ogden Intake - WN1',
        'WS-UVSC Campus - WMC',
        'DH - West Jordan Office - HCW',
        'Southwest - Beaver - SSB',
        'Bear River Health Dept - Tremonton - BRT',
        'Central Utah Health Dept - Nephi - CUN',
        'Central Utah Health Dept - Delta - CUD',
        'Central Utah Health Dept - Fillmore - CUF',
        'Central Utah Health Dept - Junction - CUJ',
        'Central Utah Health Dept - Manti - CMT',
        'Central Utah Health Dept - Loa - CUL',
        'Southeast Health Dept - Castle Dale - SCA',
        'Southeast Health Dept - Monticello - SMT',
        'Southeast Health Dept - Blanding - SBL',
        'Southeast Health Dept - Moab - SMB',
        'Central Utah Health Dept - Mt Pleasant - CMP',
        'Southwest Health Dept - Cedar City - SWC',
        'Southwest Health Dept - Kanab - SWK',
        'Southwest Health Dept - Beaver - SWB',
        'Southwest Health Dept - Hildale - SWH',
        'Southwest Health Dept - Escalante - SWE',
        'Southwest Health Dept - Panguitch - SWP',
        'Southwest Health Dept - LaVerkin - SWL',
        'Tri-County Health Dept - Roosevelt - TRR',
        'Summit County Health Dept - Park City - SCP',
        'DH- - Northern Region - Tremonton - HNT',
        'DH-Outreach Jordan Valley Hospital - HOJ',
        'DH-LINDON-BES - HML',
        'DWS- Centralized Business Office - WCB',
        'WS - South Davis - LTC North - WNQ',
        'WS-South Davis, LTC South - WNZ',
        'OUTREACH -SL CO SUBSTANCE ABUSE - WOA',
        'OUTREACH - BOYS AND GIRLS CLUB - WOB',
        'OUTREACH - CENTRAL CITY CLINIC - WOC',
        'OUTREACH - VALLEY MENTAL HEALTH - WOD',
        'OUTREACH - ELLIS SHIPP CLINIC - WOE',
        'OUTREACH - FAMILY HEALTH SERVICS - WOF',
        'OUTREACH-S L REGIONAL MED CENTER - WOH',
        'OUTREACH - JORDAN VALLEY HOSPITAL - WOJ',
        'OUTREACH-SE PUBLIC HEALTH CENTER - WOL',
        'OUTREACH - ST. MARK\'S HOSPITAL - WOM',
        'OUTREACH - NORTHWEST CLINIC - WON',
        'OUTREACH - OQUIRRH VIEW CLINIC - WOO',
        'OUTREACH-PRIMARY CHILDREN MED CNTR - WOP',
        'OUTRCH-PRIMARY CHILDREN MED CNTR - WOQ',
        'OUTREACH - U OF U MED CENTER - WOR',
        'OUTREACH-SO MAIN COMM HEALTH CNTR - WOS',
        'OUTREACH REGION - LDS HOSPITAL - WOT',
        'OUTREACH-U OF UTAH MED CENTER - WOU',
        'OUTREACH - COPPERVIEW CLINIC - WOV',
        'OUTREACH - FAMILY HEALTH SERVICES - WOW',
        'OUTRCH REGION - LDS HOSPITAL - WOY',
        'OUTREACH - HOLLADAY DSPD OFFICE - WO1',
        'OUTRCH - HOLLADAY DSPD OFFICE - WO2',
        'OUTREACH - PIONEER VALLEY HOSPITAL - WO3',
        'OUTREACH - MAGNA FACT OFFICE - WO4',
        'OUTREACH-HEALTH CLINICS OF UT SL OFF - WO5',
        'OUTREACH - SLC SCHOOL DISTRICT - WO6',
        'OUTREACH - GRANITE SCHOOL DISTRICT - WO7',
        'OUTRCH - PIONEER VALLEY HOSPITAL - WO8',
        'OUTREACH - JORDAN SCHOOL DISTRICT - WO9',
        'WS-EASTERN-AMERICAN FORK - WE1',
        'EASTERN REGION SATELLITE 4 WWS - WE2',
        'DWS-NORTHERN-SO DAVIS-LTC CENTRAL - WNY',
        'DHS-Magna Office - SCM',
        'DH-Central Reg. Murray Telecommuter - HC3',
        'DH-Central Hub Office-BES (inactive) - HNV',
        'DH-N.Ogden-Telecom-BES - HNW',
        'Bear River Health Department - BR',
        'Central Health Department - CEN',
        'Davis County Health Department - DAV',
        'Salt Lake Valley Health Department - SL',
        'Southeast Health Department - SE',
        'Summit County Health Department - SUM',
        'Southwest Health Department - SW',      
        'Tooele County Health Department - TOE',
        'Tri-County Health Department - TRI',
        'Utah County Health Department - UTA',
        'Weber-Morgan County Health Department - WM',
        'WS-Kaysville - WNK',
        'DH-Boys & GirlsS Club - HOB',
        'Provo Office for Tooele (inactive) - HMT',
        'DH-St. George Office -BES - HHS',
        'DH-Central Reg. Sandy Telecommuter - HC4',
        'DH-Outreach Region LDS Hospital - HOY',
        'DH-St. George Public Hlth Ctr - HWX',
        'WM1 - Dept of Workforce Services - WM1',
        'WM4 - Department of Work Force Services - WM4',
        'Bear River Health Dept - Brigham City - BRB',
        'TO BE DETERMINED LATER HWJ - HWJ',
        'HWK Inactive - HWK',
        'TO BE DETERMINED LATER HWL - HWL',
        'Obsolete Code N B - N B',
        'Obsolete Code N C - N C',
        'Obsolete Code NO - NO',
        'DHS-Tooele-DCFS - SCT',
        'Obsolete Code W C - W C',
        'Obsolete Code W H - W H',
        'Obsolete Code W R - W R',
        'Obsolete Code W S - W S',
        'TO BE DETERMINED LATER WHP - WHP',
        'WS-Clearfield Office (inactive) - WNF',
        'WS-Logan Office-North - WNN',
        'Obsolete Office WP - WP',
        'WS-Delta - WWD',
        'WS-Fillmore - WWF',
        'DH-State Hospital-BES - HMK',
        'WS-Loa - WWL',
        'Inactive - HWA',
        'WS-Sunset - WNS',
        'WS-Brigham East - WNG',
        'DH-Am Fork Telecommuter (inactive) - HM2',
        'WS-Fremont Office (inactive) - WCF',
        'WS-Ephraim (inactive) - WWE',
        'DH-Fremont Office-BES (inactive) - HCF',
        'WS-East Carbon - WEE',
        'DH-Outreach - SLC School District - HO6',
        'WS-Uintah County - WEU',
        'DH-CHIP Administration- Canon Bldg - HAT',
        'DH-Outreach Family Health Services - HOW',
        'DHS-West Valley City - SCW',
        'DH-Woods Cross - South Davis (inactive) - HNX',
        'DH-Roy Office - HN2',
        'DH-Outreach - SL Co Substance Abuse - HOA',
        'DH-Roosevelt Foster Care (inactive) - HMR',
        'DH-Payson Mountain View Hospital - HMV',
        'DH-Pleasant Grove Tele (inactive) - HM1',
        'Office of Recovery Services Statewide - ORS',
        'DH-Holladay DSPD Office - HO2',
        'BMC-PMHP Unit - 911',
        'Division of Health Care Financing - 901',
        'Department of Health - General - 900',
        'Bureau of Managed Health Care - 910',
        'BMC-CHEC Unit - 912',
        'DHS NORTH REGION BRIGHAM CITY - SNB',
        'Eligibility Services Operations 1 - EE1',
        'Eligibility Medical Unit 1 - EM1',
        'Eligibility Services Operations 2 - EE2',
        'Eligibility Services Operations 3 - EE3',
        'Eligibility Services Operations 4 - EE4',
        'Eligibility Services Operations 5 - EE5',
        'Eligibility Medical Unit 2 - EM2',
        'Eligibility Medical Unit 3 - EM3',
        'Eligibility Medical Unit 4 - EM4',
        'OUTREACH-CENTRAL ELIG SRV CNTR - WOX',
        'IV-E Medicaid Eligibility Team - IVE',
        'OUTREACH REGION-LDS HOSPITAL - WOZ',
        'EEM - MEDICAL ONLY - EEM',
        'EEA - ABD/QM - EEA',
        'EEJ - ESO/MED - EEJ',
        'EES - SPANISH - EES',
        'EEC - CHIP/PCN - EEC',
        'EEF - FINANCIAL/CHILD CARE - EEF',
        'EEL - LTC WAIVER - EEL',
        'Eligibility Medical Unit 5 - EM5',
        'Eligibility Services Division - ESD',
        'Testing - AAA',
    ],
    values: [
        '913',
        '914',
        '915',
        '920',
        '930',
        '940',
        '950',
        '951',
        '952',
        '960',
        '961',
        '962',
        '963',
        '964',
        '902',
        '903',
        'SCJ',
        'SSR',
        'WHR',
        'WNX',
        'WCC',
        'UKN',
        'WNR',
        'BMO',
        'SMO',
        'SAO',
        'WAO',
        'WCE',
        'WCI',
        'WWI',
        'WCW',
        'SCK',
        'HWH',
        'WEM',
        'HW1',
        'HNP',
        'HOE',
        'HW2',
        'HWD',
        'HEY',
        'HO7',
        'HMH',
        'HOV',
        'HNJ',
        'HNI',
        'HEC',
        'HOP',
        'WWN',
        'HC1',
        'HWB',
        'HOO',
        'HO4',
        'HEM',
        'HO5',
        'HM3',
        'WCT',
        'HO3',
        'WER',
        'HWC',
        'WNA',
        'HNA',
        'HCT',
        'HEZ',
        'WNB',
        'HWN',
        'HEB',
        'HEV',
        'HNB',
        'HNL',
        'WWM',
        'HWR',
        'HCX',
        'HO1',
        'HER',
        'HEP',
        'WEV',
        'WSC',
        'WWC',
        'WSA',
        'HND',
        'WSB',
        'HCV',
        'WND',
        'HWS',
        'WWR',
        'HCH',
        'WNL',
        'WWS',
        'WC4',
        'WC5',
        'WC8',
        'WC6',
        'WC2',
        'WC3',
        'WC7',
        'WEB',
        'HWM',
        'HMM',
        'C P',
        'CC',
        'H00',
        'E C',
        'E O',
        'E P',
        'E V',
        'HCP',
        'HNH',
        'HWF',
        'HWG',
        'WWJ',
        'HOF',
        'HWP',
        'HWV',
        'HOT',
        'HMC',
        'SNO',
        'HOL',
        'HC2',
        'HOS',
        'SNC',
        'HOU',
        'HEF',
        'HNM',
        'SCH',
        'HOQ',
        'HWE',
        'HNF',
        'HNN',
        'HCD',
        'WCD',
        'HCR',
        'WCR',
        'HCM',
        'WCM',
        'HCS',
        'WCS',
        'HNO',
        'WNO',
        'WNC',
        'HMP',
        'WMP',
        'HMO',
        'WMO',
        'HMA',
        'WMA',
        'WEP',
        'HAO',
        'WC1',
        'E M',
        'HN1',
        'HNS',
        'N O',
        'W P',
        'HO8',
        'C C',
        'C T',
        'WMY',
        'E R',
        'WWK',
        'HMU',
        'WCV',
        'SEC',
        'HOR',
        'SNY',
        'WC9',
        'HCC',
        'WEO',
        'WWB',
        'HOH',
        'SER',
        'WWP',
        'SMP',
        'HNC',
        'HON',
        'SCN',
        'WMV',
        'SMS',
        'SSW',
        'SMH',
        'WMH',
        'HOM',
        'SCY',
        'HOC',
        'WEC',
        'SCC',
        'SCS',
        'HNR',
        'HNE',
        'HNZ',
        'MHC',
        'LHD',
        'FC',
        'YC',
        'SA',
        'HOD',
        'WAS',
        'SCX',
        'HO9',
        'WN1',
        'WMC',
        'HCW',
        'SSB',
        'BRT',
        'CUN',
        'CUD',
        'CUF',
        'CUJ',
        'CMT',
        'CUL',
        'SCA',
        'SMT',
        'SBL',
        'SMB',
        'CMP',
        'SWC',
        'SWK',
        'SWB',
        'SWH',
        'SWE',
        'SWP',
        'SWL',
        'TRR',
        'SCP',
        'HNT',
        'HOJ',
        'HML',
        'WCB',
        'WNQ',
        'WNZ',
        'WOA',
        'WOB',
        'WOC',
        'WOD',
        'WOE',
        'WOF',
        'WOH',
        'WOJ',
        'WOL',
        'WOM',
        'WON',
        'WOO',
        'WOP',
        'WOQ',
        'WOR',
        'WOS',
        'WOT',
        'WOU',
        'WOV',
        'WOW',
        'WOY',
        'WO1',
        'WO2',
        'WO3',
        'WO4',
        'WO5',
        'WO6',
        'WO7',
        'WO8',
        'WO9',
        'WE1',
        'WE2',
        'WNY',
        'SCM',
        'HC3',
        'HNV',
        'HNW',
        'BR',
        'CEN',
        'DAV',
        'SL',
        'SE',
        'SUM',
        'SW',      
        'TOE',
        'TRI',
        'UTA',
        'WM',
        'WNK',
        'HOB',
        'HMT',
        'HHS',
        'HC4',
        'HOY',
        'HWX',
        'WM1',
        'WM4',
        'BRB',
        'HWJ',
        'HWK',
        'HWL',
        'N B',
        'N C',
        'NO',
        'SCT',
        'W C',
        'W H',
        'W R',
        'W S',
        'WHP',
        'WNF',
        'WNN',
        'WP',
        'WWD',
        'WWF',
        'HMK',
        'WWL',
        'HWA',
        'WNS',
        'WNG',
        'HM2',
        'WCF',
        'WWE',
        'HCF',
        'WEE',
        'HO6',
        'WEU',
        'HAT',
        'HOW',
        'SCW',
        'HNX',
        'HN2',
        'HOA',
        'HMR',
        'HMV',
        'HM1',
        'ORS',
        'HO2',
        '911',
        '901',
        '900',
        '910',
        '912',
        'SNB',
        'EE1',
        'EM1',
        'EE2',
        'EE3',
        'EE4',
        'EE5',
        'EM2',
        'EM3',
        'EM4',
        'WOX',
        'IVE',
        'WOZ',
        'EEM',
        'EEA',
        'EEJ',
        'EES',
        'EEC',
        'EEF',
        'EEL',
        'EM5',
        'ESD',
        'AAA',
    ]
}

const languageOptions = {
    labels: [
        'ABKHAZIAN - AB',
        'AFAN (OROMO) - OM',
        'AFAR - AA',
        'AFRIKAANS - AF',
        'ALBANIAN - SQ',
        'SIGN LANGUAGES - ASL',
        'AMHARIC - AM',
        'APACHE - AP',
        'APACHE - LN15',
        'ARABIC - AR',
        'ARMENIAN - HY',
        'ASSAMESE - AS',
        'AYMARA - AY',
        'AZERBAIJANI - AZ',
        'BASHKIR - BA',
        'BASQUE - EU',
        'BENGALI; BANGLA - BN',
        'BHUTANI - DZ',
        'BIHARI - BH',
        'BISLAMA - BI',
        'BOSNIAN - BS',
        'BRETON - BR',
        'BULGARIAN - BG',
        'BURMESE - MY',
        'BYELORUSSIAN - BE',
        'CAMBODIAN - KM',
        'CAMBODIAN - LN10',
        'CATALAN - CA',
        'CHINESE - ZH',
        'CHUUKESE - CH',
        'CORSICAN - CO',
        'CREOLE - CR',
        'CROATIAN - HR',
        'CZECH - CS',
        'DANISH - DA',
        'DUTCH - NL',
        'ENGLISH - LN1',
        'ESPERANTO - EO',
        'ESTONIAN - ET',
        'FAROESE - FO',
        'FIJI - FJ',
        'FINNISH - FI',
        'FRENCH - FR',
        'FRENCH - LN4',
        'FRISIAN - FY',
        'GALICIAN - GL',
        'GEORGIAN - KA',
        'GERMAN - DE',
        'GERMAN - LN2 ',
        'GREEK - EL',
        'GREENLANDIC - KL',
        'GUARANI - GN',
        'GUJARATI - GU',
        'HAUSA - HA',
        'HEBREW - IW',
        'HINDI - HI',
        'HUNGARIAN - HU',
        'ICELANDIC - IS',
        'INDONESIAN - IN',
        'INTERLINGUA - IA',
        'INTERLINGUE - IE',
        'INUKTITUT - IU',
        'INUPIAK - IK',
        'IRISH - GA',
        'IRISH - LN3',
        'ITALIAN - IT',
        'ITALIAN - LN6',
        'JAPANESE - JA',
        'JAPANESE - LN12',
        'JAVANESE - JV',
        'KANNADA - KN',
        'KAREN - LN17',
        'KASHMIRI - KS',
        'KAZAKH - KK',
        'KINYARWANDA - RW',
        'KIRGHIZ - KY',
        'KISWAHILI - KI',
        'KOREAN - KO',
        'KURDISH - KU',
        'KURUNDI - RN',
        'LAO - LO',
        'LATIN - LA',
        'LATVIAN;LETTISH - LV',
        'LINGALA - LN',
        'LITHUANIAN - LT',
        'MAAY MAAY - MM',
        'MACEDONIAN - MK',
        'MALAGASY - MG',
        'MALAY - MS',
        'MALAYALAM - ML',
        'MALTESE - MT',
        'MAORI - MI',
        'MARATHI - MR',
        'MARSHALLISE - MA',
        'MASHUNGULI - MH',
        'MOLDAVIAN - MO',
        'MONGOLIAN - MN',
        'NAURU - NA',
        'NAVAJO - NV',
        'NAVAJO - LN14',
        'NEPALI - NE',
        'NORWEGIAN - NO',
        'OCCITAN - OC',
        'ORIYA - OR',
        'PASHTO;PUSHTO - PS',
        'PERSIAN (farsi) - FA',
        'POLISH - PL',
        'PORTUGUESE - PT',
        'PUNJABI - PA',
        'QUECHUA - QU',
        'RHAETO-ROMANCE - RM',
        'ROMANIAN - RO',
        'RUSSIAN - RU',
        'RUSSIAN - LN13',
        'SAMOAN - SM',
        'SANGO - SG',
        'SANSKRIT - SA',
        'SCOTS GAELIC - GD',
        'SERBIAN - SR',
        'SERBO-CROATIAN - SH',
        'SESOTHO - ST',
        'SETSWANA - TN',
        'SHONA - SN',
        'SINDHI - SD',
        'SINGHALESE - SI',
        'SISWATI - SS',
        'SLOVAK - SK',
        'SLOVENIAN - SL',
        'SOMALI - SO',
        'SPANISH - LN5',
        'SUNDANESE - SU',
        'SWAHILI - SW',
        'SWEDISH - SV',
        'TAGALOG - TL',
        'TAJIK - TG',
        'TAMIL - TA',
        'TATAR - TT',
        'TELUGU - TE',
        'THAI - TH',
        'TIBETAN - BO',
        'TIGRINYA - TI',
        'TO BE DEFINED - ER',
        'TONGA - TO',
        'TSONGA - TS',
        'TURKISH - TR',
        'TURKMEN - TK',
        'TWI - TW',
        'UKRAINIAN - UK',
        'URDU - UR',
        'UTE - UT',
        'UYGHUR - UG',
        'UZBEK - UZ',
        'VIETNAMESE - VI',
        'VIETNAMESE - LN11',
        'VOLAPUK - VO',
        'WELSH - CY',
        'WOLOF - WO',
        'XHOSA - XH',
        'YIDDISH - JI',
        'YORUBA - YO',
        'ZHUANG - ZA',
        'ZULU - ZU',
        'SIGN LANGUAGES - LN7',
        'LAO  - LN8',
        'MISCELLANEOUS LANGUAGES - LN9',
        'MISCELLANEOUS LANGUAGES - ER',
        'EWE - EW',
        'MISCELLANEOUS LANGUAGES - PW',
        'MISCELLANEOUS LANGUAGES - LN16',
        'PERSIAN (farsi) - LN18',
        'BHUTANI - LN19',
        'PERSIAN (farsi) - LN20',
        'MULTIPLE LANGUAGES - ALL',
        'INDO- ARYENNES - RH',
        'DINKA - DI',
    ],
    values: [
        'AB',
        'OM',
        'AA',
        'AF',
        'SQ',
        'ASL',
        'AM',
        'AP',
        'LN15',
        'AR',
        'HY',
        'AS',
        'AY',
        'AZ',
        'BA',
        'EU',
        'BN',
        'DZ',
        'BH',
        'BI',
        'BS',
        'BR',
        'BG',
        'MY',
        'BE',
        'KM',
        'LN10',
        'CA',
        'ZH',
        'CH',
        'CO',
        'CR',
        'HR',
        'CS',
        'DA',
        'NL',
        'LN1',
        'EO',
        'ET',
        'FO',
        'FJ',
        'FI',
        'FR',
        'LN4',
        'FY',
        'GL',
        'KA',
        'DE',
        'LN2 ',
        'EL',
        'KL',
        'GN',
        'GU',
        'HA',
        'IW',
        'HI',
        'HU',
        'IS',
        'IN',
        'IA',
        'IE',
        'IU',
        'IK',
        'GA',
        'LN3',
        'IT',
        'LN6',
        'JA',
        'LN12',
        'JV',
        'KN',
        'LN17',
        'KS',
        'KK',
        'RW',
        'KY',
        'KI',
        'KO',
        'KU',
        'RN',
        'LO',
        'LA',
        'LV',
        'LN',
        'LT',
        'MM',
        'MK',
        'MG',
        'MS',
        'ML',
        'MT',
        'MI',
        'MR',
        'MA',
        'MH',
        'MO',
        'MN',
        'NA',
        'NV',
        'LN14',
        'NE',
        'NO',
        'OC',
        'OR',
        'PS',
        'FA',
        'PL',
        'PT',
        'PA',
        'QU',
        'RM',
        'RO',
        'RU',
        'LN13',
        'SM',
        'SG',
        'SA',
        'GD',
        'SR',
        'SH',
        'ST',
        'TN',
        'SN',
        'SD',
        'SI',
        'SS',
        'SK',
        'SL',
        'SO',
        'LN5',
        'SU',
        'SW',
        'SV',
        'TL',
        'TG',
        'TA',
        'TT',
        'TE',
        'TH',
        'BO',
        'TI',
        'ER',
        'TO',
        'TS',
        'TR',
        'TK',
        'TW',
        'UK',
        'UR',
        'UT',
        'UG',
        'UZ',
        'VI',
        'LN11',
        'VO',
        'CY',
        'WO',
        'XH',
        'JI',
        'YO',
        'ZA',
        'ZU',
        'LN7',
        'LN8',
        'LN9',
        'ER',
        'EW',
        'PW',
        'LN16',
        'LN18',
        'LN19',
        'LN20',
        'ALL',
        'RH',
        'DI',
    ]
}
const raceCodeOptions = {
    labels: [
        'AI Alaska Native or American Indian- Pending',
        'AN Alaska Native or American Indian- Not Verified',
        'AS Asian',
        'ASI Asian Indian',
        'AV Alaska Native or American Indian -Verified',
        'BL Black or African American',
        'CH Chinese',
        'FI Filipino',
        'GC Guamanian or Chamorro',
        'HI Hispanic',
        'JA Japanese',
        'KO Korean',
        'NH Native Hawaiian',
        'OA Other Asian',
        'OPI Other Pacific Islander',
        'PI Native Hawaiian or Other Pacific Islander',
        'OT Other',
        'SA Samoan',
        'UN Undeclared',
        'VI Vietnamese',
        'WH White/Non-Hispanic',
    ],
    values: [
        'AI',
        'AN',
        'AS',
        'ASI',
        'AV',
        'BL',
        'CH',
        'FI',
        'GC',
        'HI',
        'JA',
        'KO',
        'NH',
        'OA',
        'OPI',
        'PI',
        'OT',
        'SA',
        'UN',
        'VI',
        'WH',]
}

const SPMIndicatorOptions = {
    labels: [
        'SM1',
        'SM2',
        'SM3',
    ],
    values: [
        'SM1',
        'SM2',
        'SM3',
    ]
}

const spenddownIndicatorOptions = {
    labels: [
        'Yes - Met, but not through bills (cash, deductions e.g. insurance payment)',
        'No - Not Met',
        'X - Cost of Care met with Incurred Bills'
    ],
    values: [
        'Y',
        'N',
        'X'
    ]
}

export default function useOptions () {
    return {
        YNOptions,
        racOptions,
        countyOptions,
        benefitSubTypeOptions,
        incarcerationStatusOptions,
        denialClosureOptions,
        districtOfficeOptions,
        languageOptions,
        raceCodeOptions,
        SPMIndicatorOptions,
        spenddownIndicatorOptions,
    }
}