const YNOptions = {
    labels: ['Yes', 'No'],
    values: ['Y', 'N']
}

const racOptions = {
    labels: [
        'A1 - Foster care Medicaid, Title IVE ',
        'A18 - Foster Care Independent Living Medicaid, age 18 through 20',
        'A19 - Former Foster Care Medicaid, 18 to 26',
        'A1A - Subsidized adoption Medicaid, Title IV-E',
        'A21 - Family Medicaid - Adult (AFDC)',
        'A22 - Family Medicaid - Child (LIFC)',
        'A23 - Family Medicaid - Adult (AFDC)',
        'A31 - Family Medicaid - Adult (AFDC)',
        'A32 - Family Medicaid - Child (LIFC)',
        'A35 - Family Medicaid - Child (LIFC)',
        'A36 - Family Medicaid, Adult Parent/ Caretaker Relative',
        'A37 - Family Medicaid, Adult Parent/ Caretaker Relative ',
        'A4 - Family Medicaid - Child (AFDC)',
        'A42 - Adult, Medicaid, Chronically Homeless Individuals',
        'A43 - Adult Medicaid, Justice Involved Individuals',
        'A44 - Adult Medicaid, Individuals Needing Substance Abuse or Mental Health Treatment',
        'A5 - Family Medicaid - Child (AFDC)',
        'A51 - Family Medicaid, Adult, 4-month spousal support increase',
        'A52 - Family Medicaid, Child, 4-month spousal support increase',
        'A55 - Family Medicaid, Child, 12-month transitional earned income increase',
        'A57 - Family Medicaid, Adult, 12-month transitional earned income increase',
        'A61 - Family Medicaid - Adult (4 Month Extension)',
        'A62 - Family Medicaid - Child (4 month Transitional-Earned Income increase)',
        'A63 - Family Medicaid - Adult (9 Month Extension)',
        'A64 - Family – Child, 9 month Transitional-exhausted time frame for $30 or 1/3 earned income disregard',
        'A65 - Family Medicaid - Child (12 month Transitional-Earned Income increase)',
        'A66 - Child Medicaid (< 2 months of age born to mom on Medicaid)',
        'A67 - Child Medicaid (< 3 months of age born to mom on Medicaid)',
        'A68 - Family Medicaid - Adult (12 Month Extension)',
        'A69 - Child Medicaid, 0 to 1, born to a mom on Medicaid',
        'A7 - Pregnant Woman Medicaid, Spenddown',
        'A8 - Family Medicaid - Child (AFDC)',
        'A80 - Child Medicaid, ages 6 through 18',
        'A81 - Child Medicaid, ages 0 through 5',
        'A82 - Pregnant Woman Medicaid - 139% FPL',
        'A83 - Nursing Home Medicaid - Child -ancillary only',
        'A84 - Nursing Home Medicaid - Pregnant - ancillary only',
        'A94 - Nursing Home Medicaid - Aged SSI or Protected group',
        'A95 - Nursing Home Medicaid, Aged, ancillary only',
        'AA4 - Nursing Home Medicaid, Blind SSI and Protected groups',
        'AA5 - Nursing Home Medicaid, Blind and Protected groups, ancillary only',
        'AB4 - Nursing Home Medicaid, Disabled SSI and Protected groups',
        'AB5 - Nursing Home Medicaid, Disabled, ancillary only ',
        'ABF - Foster Care Medicaid, Blind, non IVE, SSI or Protected groups ',
        'AC3 - Aged Medicaid - SSI',
        'AC4 - Aged Medicaid (SSI)',
        'AC8 - Aged Medicaid - 1619b',
        'AC9 - Aged Medicaid - Pickle Amendment',
        'ACF - Foster Care Medicaid (non-IVE, ages 6-18) ',
        'AD1 - Blind Medicaid, SSI',
        'AD2 - Blind Medicaid (SSI)',
        'AD8 - Blind Medicaid, 1619(b)',
        'AD9 - Blind Medicaid, Pickle Amendment',
        'ADF - Foster Care Medicaid, non-IVE, Disabled-SSI or SSI protected',
        'AE1 - Disabled Medicaid, SSI',
        'AE2 - Disabled Medicaid (SSI)',
        'AE8 - Disabled Medicaid, 1619(b) ',
        'AE9 - Disabled Medicaid, Pickle Amendment',
        'AF1 - Disabled Medicaid, Disabled Adult Child age 18 or older',
        'AF2 - Disabled Medicaid (Widow(er)) (entitled to Medicare)  ',
        'AG1 - Blind Medicaid, Disabled Adult Child age 18 or older',
        'AH2 - Aged Medicaid (Widow(er))',
        'AH3 - Disabled Medicaid, Widow(er) age 60 through 64 ',
        'AH4 - Disabled Medicaid, Disabled Widow(er) age 50 through 59',
        'AJ1 - Disabled Medicaid - Child (K Kids) ',
        'AK1 - IV-E Kinship Guardianship Medicaid',
        'AUT - Autism Waiver',
        'B12 - Nursing home Medicaid, Aged ',
        'B13 - Aged Medicaid, income less than or equal to 100% FPL',
        'B14 - Nursing Home Medicaid, Pregnant Woman income less than or equal to 300% FBR',
        'B21 - Nursing Home Medicaid - Blind ',
        'B22 - Nursing Home Medicaid, Blind',
        'B32 - Nursing Home Medicaid, Disabled ',
        'B33 - Disabled Medicaid, income less than or equal to 100% FPL',
        'B35 - Disabled Medicaid, MWI, Assets less than MWI criteria',
        'B36 - Disabled Medicaid, MWI, assets less than resource limit for 100% FPL',
        'B37 - Disabled Medicaid, MWI, assets over resource limit for 100% FPL and less than MWI limit',
        'B39 - Breast and Cervical Cancer Medicaid',
        'B4 - Aged Medicaid, not on SSI',
        'B5 - Blind Medicaid, not on SSI',
        'B6 - Disabled Medicaid, not on SSI',
        'B71 - Family Medicaid - Adult (AFDC)',
        'B72 - Child, not AFDC financial, not institutionalized',
        'B74 - Child, not AFDC financial, not institutionalized',
        'B81 - Child, not AFDC financial, not institutionalized',
        'B91 - Subsidized adoption Medicaid, non-IVE ',
        'BCF - Foster Care Medicaid (non-IVE)',
        'BDC - Foster Care Medicaid-non-IVE, disabled, income less than or equal to 100% FPL',
        'BDW - Foster Care Medicaid, non-IVE child, disabled, MWI',
        'BYB - Baby Your Baby, Presumptive Pregnant Woman',
        'C12 - Nursing Home Medicaid, Aged, income over 300% FBR',
        'C13 - Nursing Home Medicaid, Child, income over 300% FBR',
        'C14 - Nursing Home Medicaid, Pregnant, income over 300% FBR',
        'C22 - Nursing Home Medicaid, Blind, income over 300% FBR',
        'C32 - Nursing Home Medicaid, Disabled, income over 300% FBR',
        'C43 - Aged Medicaid, spenddown',
        'C53 - Blind Medicaid, non-SSI, spenddown, income > 100% FPL',
        'C63 - Disabled Medicaid, spenddown',
        'C7 - Pregnant Woman Medicaid (Spenddown)',
        'C71 - Family Medicaid, Adult, spenddown $0',
        'C72 - Family Medicaid, Child, spenddown $0',
        'C73 - Family Medicaid, Adult, spenddown',
        'C74 - Family Medicaid, Child, spenddown ',
        'C81 - Family Medicaid, Child, spenddown $0',
        'C82 - Family Medicaid, Child, spenddown',
        'C95 - Nursing Home Medicaid, Aged, ancillary, spenddown',
        'CA5 - Nursing Home Medicaid, Disabled, ancillary, spenddown',
        'CB5 - Nursing Home Medicaid, Blind, ancillary, spenddown',
        'CBF - Foster Care Medicaid, Blind, non-IVE, spenddown',
        'CCF - Foster Care Medicaid, Child, non-IVE foster care',
        'CD1 - Community Supports Waiver, Aged, income over 300% FBR',
        'CD2 - Community Supports Waiver, Blind, income over 300% FBR',
        'CD3 - Community Supports Waiver, Disabled, income over 300% FBR',
        'CD4 - Community Supports Waiver, Child, income over 300% FBR',
        'CD5 - Community Supports Waiver, Adult, income over 300% FBR',
        'CDF - Foster Care Medicaid, Disabled, spenddown > $0',
        'CFC - Foster Care Medicaid, Child or pregnant, spenddown > $0',
        'CI1 - CHIP Plan A',
        'CI2 - CHIP Plan B',
        'CI3 - CHIP Plan C',
        'CI4 - Utah Premium Partnership, Child, Employer sponsored medical, dental',
        'CI5 - Utah Premium Partnership, Child, Employer sponsored medical, CHIP dental',
        'CI6 - Utah Premium Partnership, Child, COBRA medical/ dental, started prior to application',
        'CI7 - Utah Premium Partnership, Child, COBRA medical, started before appl, CHIP dental',
        'CI8 - Utah Premium Partnership, Child, COBRA medical/ dental started after application',
        'CI9 - Utah Premium Partnership, Child, COBRA medical, started after appl, CHIP dental',
        'CIP - CHIP Presumptive',
        'CT2 - Tech Dependent Waiver, Blind, income over 300% FBR',
        'CT3 - Tech Dependent Waiver, Disabled, income over 300% FBR',
        'CT4 - Tech Dependent Waiver, Child, income over 300% FBR',
        'CWA - Aging waiver, income over 300% FBR',
        'D1 - Custody Medical Care',
        'D2 - Juvenile Justice System',
        'D3 - Medical Review Board',
        'D4 - General Assistance State Supplemental Payment',
        'E - Migrant Medical',
        'EV - Katrina Evacuee',
        'EVQ - Katrina Evacuee - QMB',
        'I18 - Foster care Independent Living Medicaid, 18 through 20, emergency only',
        'IA1 - Aged Medicaid - Emergency (Income < SSI rate)',
        'IA2 - Aged Medicaid, emergency only, spenddown',
        'IA3 - Aged Medicaid, emergency only, income less than or equal to 100% FPL',
        'IA9 - Qualified Medicare Beneficiary, Aged',
        'IB1 - Blind Medicaid - Emergency ',
        'IB2 - Blind Medicaid, emergency only, may or may not have a spenddown',
        'IB9 - Qualified Medicare Beneficiary, Blind',
        'IC1 - Child Medicaid - Emergency ',
        'IC2 - Child, emergency only, spenddown',
        'ICF - Foster care Medicaid, non-IVE, emergency only',
        'ID1 - Disabled Medicaid - Emergency (Income < SSI rate) ',
        'ID2 - Disabled Medicaid, emergency only, spenddown',
        'ID3 - Disabled Medicaid, emergency only, income less than or equal to 100% FPL',
        'ID4 - Disabled Medicaid, MWI, emergency only, ',
        'ID5 - Breast and cervical cancer Medicaid, emergency only',
        'ID9 - Qualified Medicare Beneficiary, Disabled',
        'IF1 - Family Medicaid, Adult, emergency only',
        'IF2 - Family Medicaid, Adult, emergency only, spenddown',
        'IF5 - Family Medicaid - Emergency (Child)',
        'IF6 - Family Medicaid, Child, emergency only, spenddown',
        'IF7 - Pregnant woman Medicaid, emergency only, spenddown',
        'IF8 - Child Medicaid, age 0 through 5',
        'IF9 - Pregnant Woman Medicaid, emergency only',
        'IFP - Pregnant Woman Medicaid - Emergency (High Risk)',
        'IO9 - Disabled, QMB only, Medicare entitled under Railroad or government employment',
        'IP1 - Child Medicaid, age 6 through 18, emergency only',
        'MCC - Medically Complex Waiver, Child',
        'MP1 - Child Medicaid - Presumptive, ages 0 through 5',
        'MP2 - Child Medicaid - Presumptive, ages 6 through 18',
        'P19 - Former Foster Care-Presumptive Eligibility, 18 through 25',
        'P82 - Pregnant Woman Medicaid (High Risk)',
        'PC1 - Primary Care Network, adult with dependent children',
        'PC2 - Primary Care Network, adult without dependent children',
        'PC3 - Utah Premium Partnership, Adult with dependent child',
        'PC4 - Utah Premium Partnership, Adult w/o dependent child',
        'PC5 - Utah Premium Partnership, Adult w/dependent child, COBRA started before appl',
        'PC6 - Utah Premium Partnership, Adult w/o dependent child, COBRA started before appl',
        'PC7 - Utah Premium Partnership, Adult w/dependent child, COBRA started after appl.',
        'PC8 - Utah Premium Partnership, Adult w/o dependent child, COBRA started after application',
        'PCR - Parent Caretaker Relative Medicaid, Presumptive',
        'PFM - Family Medicaid - Pregnant',
        'Q12 - Nursing Home Medicaid and QMB, Aged',
        'Q13 - Aged Medicaid and QMB, income less than or equal to 100% FPL',
        'Q22 - Nursing Home Medicaid and QMB, Blind',
        'Q32 - Disabled Medicaid and QMB, institutional, not SSI, income less than or equal to 100% FPL',
        'Q33 - Disabled Medicaid and QMB, income less than or equal to 100% FPL',
        'Q35 - Disabled Medicaid, MWI and QMB',
        'Q37 - Family Medicaid, PCR and QMB',
        'Q42 - Adult, Medicaid, Chronically Homeless Individuals & QMB',
        'Q43 - Adult Medicaid, Justice Involved Individuals  QMB',
        'Q44 - Adult Medicaid, Individuals Needing Substance Abuse or Mental Health Treatment & QMB',
        'Q51 - Family Medicaid and QMB, Adult, 4-month spousal support',
        'Q53 - Blind Medicaid and QMB, spenddown $0 if income is > BMS and <100% FPL',
        'Q57 - Family Medicaid and QMB, Adult, 12-month earned income increase',
        'Q71 - Family Medicaid and QMB - Adult',
        'Q73 - Family Medicaid and QMB, Adult, spenddown',
        'Q82 - Pregnant Woman Medicaid and QMB',
        'Q94 - Nursing Home Medicaid and QMB, Aged SSI or Protected group',
        'Q95 - Aged Medicaid, ancillary only, QMB, institutional or waiver, income less than or equal to 300% FBR',
        'QA1 - Family Medicaid and QMB - Adult',
        'QA2 - Family Medicaid and QMB - Adult ',
        'QA4 - Nursing Home Medicaid and QMB, Blind, SSI and Protected groups',
        'QA5 - Nursing Home Medicaid and QMB, Blind, ancillary only',
        'QA6 - Family Medicaid and QMB - Adult (Parent/Caretaker Relative)',
        'QB1 - Acquired Brain Injury Waiver and QMB, Aged',
        'QB2 - Acquired Brain Injury Waiver and QMB, Disabled',
        'QB3 - Acquired Brain Injury Waiver and QMB, Blind',
        'QB4 - Aged, spenddown $0',
        'QB5 - Blind, spenddown $0 and QMB',
        'QB6 - Disabled, spenddown $0',
        'QC1 - Adult, spenddown $0',
        'QC3 - Aged Medicaid and QMB, SSI',
        'QC8 - Aged Medicaid and QMB, 1619(b)',
        'QC9 - Aged Medicaid and QMB, Pickle Amendment',
        'QCC - Medically Complex child waiver and QMB, Child ',
        'QD1 - Blind Medicaid and QMB, SSI',
        'QD2 - Community Supports Waiver and QMB, Disabled ',
        'QD3 - Community Supports waiver and QMB, Blind',
        'QD4 - Community Supports waiver and QMB - Child',
        'QD6 - Community Supports Waiver and QMB, Aged',
        'QD8 - Blind Medicaid and QMB, 1619(b) ',
        'QD9 - Blind Medicaid and QMB, Pickle Amendment',
        'QE1 - Disabled Medicaid and QMB, SSI ',
        'QE2 - Family Medicaid and QMB - Adult (4 Month Extension)',
        'QE3 - Family Medicaid and QMB - Adult ( 9 or 12 Month Extension)',
        'QE8 - Disabled Medicaid and QMB, 1619(b) ',
        'QE9 - Disabled Medicaid and QMB, Pickle Amendment',
        'QF1 - Disabled Medicaid and QMB, Disabled Adult Child age 18 and older',
        'QF2 - Disabled Medicaid and QMB [Widow(er)]',
        'QG1 - Blind Medicaid and QMB, Disabled Adult Child age 18 and older',
        'QH2 - Aged Medicaid and QMB [Widow(er)]',
        'QN1 - New Choices Waiver and QMB,  Aged, SSI or Protected groups',
        'QN2 - New Choices Waiver and QMB, Aged, income less than or equal to 100% FPL',
        'QN5 - New Choices Waiver and QMB, Disabled, SSI or Protected groups ',
        'QN6 - New Choices Waiver and QMB, Disabled, with income less than or equal to 100% FPL',
        'QP1 - Physical Disabilities waiver and QMB, Aged, income less than or equal to 100% FPL',
        'QP2 - Physical Disabilities waiver and QMB, Blind, income less than or equal to 100% FPL',
        'QP3 - Physical Disabilities waiver and QMB, Disabled, income less than or equal to 100% FPL',
        'QQ4 - Nursing Home Medicaid and QMB, Disabled, SSI ',
        'QQ5 - Nursing Home Medicaid and QMB, Disabled, ancillary only',
        'QT2 - Tech Dependent Waiver and QMB, Disabled ',
        'QT3 - Tech Dependent Waiver and QMB, Blind ',
        'QT4 - Child Medicaid, Technology waiver,  and QMB with income less than or equal to 100% FPL',
        'QWA - Aging Waiver Medicaid and QMB',
        'RM1 - Refugee Medical, Adult',
        'RM2 - Refugee Medical, Child',
        'TB - Tuberculosis Medicaid',
        'TD1 - Tech Dependent Waiver, Aged',
        'TD2 - Tech Dependent Waiver, Disabled',
        'TD3 - Tech Dependent Waiver, Blind',
        'TD4 - Tech Dependent Waiver, Child',
        'TD5 - Tech Dependent Waiver, Adult',
        'WAI -  Aging Waiver',
        'WB1 - Acquired Brain Injury Waiver, Aged',
        'WB2 - Acquired Brain Injury Waiver, Disabled',
        'WB3 - Acquired Brain Injury Waiver, Blind',
        'WB4 - Acquired Brain Injury Waiver, Adult',
        'WB5 - Acquired Brain Injury waiver, Aged, income > 300% FBR',
        'WB6 - Acquired Brain Injury waiver, Disabled, income > 300% FBR',
        'WB7 - Acquired Brain Injury waiver, Blind, income > 300% FBR',
        'WD1 - Community Supports Waiver, Aged, income less than or equal to 300% FBR',
        'WD2 - Community Supports Waiver, Disabled, income less than or equal to 300% FBR',
        'WD3 - Community Supports Waiver, Blind, income less than or equal to 300% FBR',
        'WD4 - Community Supports Waiver, Child, income less than or equal to 300% FBR',
        'WD5 - Community Supports Waiver, Adult, income less than or equal to 300% FBR',
        'WN1 - New Choices Waiver, Aged, SSI or Protected groups',
        'WN2 - New Choices Waiver, Aged, income less than or equal to 100% FPL',
        'WN3 - New Choices waiver, Aged, income > 300% FBR',
        'WN4 - New Choices Waiver, Aged, income less than or equal to 300% FBR',
        'WN5 - New Choices Waiver - Disabled, SSI or Protected groups',
        'WN6 - New Choices Waiver, Disabled, income less than or equal to 100% FPL',
        'WN7 - New Choices Waiver, Disabled, MWI',
        'WN8 - New Choices Waiver, Disabled, income > 300% FBR',
        'WN9 - New Choices Waiver, Disabled, income less than or equal to 300% FBR',
        'WP1 -  Physical Disabilities waiver, Aged',
        'WP2 - Physical Disabilities Waiver, Blind',
        'WP3 - Physical Disabilities Waiver, Disabled',
        'WP4 -  Physical Disabilities waiver, Aged, income > 300% FBR',
        'WP5 - Physical Disabilities Waiver, Blind, income > 300% FBR',
        'WP6 - Physical Disabilities Waiver, Disabled, income > 300% FBR',
        'CWD - Aging waiver, Disabled, income over 300% FBR',
        'QWD - Aging Waiver, Disabled, Medicaid and QMB',
        'WAD - Aging Waiver, Disabled',
        'E01 - Adult Expansion, age 21 to 64, adult w/ dependent children',
        'E02 - Adult Expansion, age 19 to 20, adult w/ dependent',
        'E03 - Adult Expansion, age 21 to 64, 100%, adult w/ dependent children',
        'E04 - Adult Expansion, age 19 to 20, 100%, adult w/ dependent children',
        'E07 - Adult Expansion, age 21 to 64, 100%, adult w/o dependent children',
        'E08 - Adult Expansion, age 19 to 20, 100%, adult w/o dependent children',
        'EP1 - Adult Expansion, age 21 to 64, 133%, Presumptive, adult w/ dependent children',
        'EP2 - Adult Expansion, age 19 to 20, 133%, Presumptive, adult w/ dependent children',
        'EP3 - Adult Expansion, age 21 to 64, 133%, Presumptive, adult w/o dependent children',
        'EP4 - Adult Expansion, age 19 to 20, 133%, Presumptive, adult w/o dependent children',
        'EE1 - Adult Expansion, age 19 to 64, adult w/ dependent children, emergency only',
        'EE2 - Adult Expansion, age 19 to 64, 133%, adult w/ dependent children, emergency only',
        'EE3 - Adult Expansion, age 19 to 64, 133%, adult w/o dependent children, emergency only',
        'E05 - Adult Expansion, age 21 to 64, 133%, adult w/ dependent children',
        'E06 - Adult Expansion, age 19 to 20, 133%, adult w/ dependent children',
        'ES3 - Adult Expansion, age 21 to 64, 100%, ESI, adult w/ dependent children',
        'ES4 - Adult Expansion, age 19 to 20, 100%, ESI, adult w/ dependent children',
        'ES5 - Adult Expansion, age 21 to 64, 133%, ESI, adult w/ dependent children',
        'ES6 - Adult Expansion, age 19 to 20, 133%, ESI, adult w/ dependent children',
        'E09 - Adult Expansion, age 21 to 64, 133%, adult w/o dependent children',
        'E0A - Adult Expansion, age 19 to 20, 133%, adult w/o dependent children',
        'ES7 - Adult Expansion, age 21 to 64, 100%, ESI, adult w/o dependent children',
        'ES8 - Adult Expansion, age 19 to 20, 100%, ESI, adult w/o dependent children',
        'ES9 - Adult Expansion, age 21 to 64, 133%, ESI, adult w/o dependent',
        'ESA - Adult Expansion, age 19 to 20, 133%, ESI, adult w/o dependent children',
        'EFA - Adult Expansion, age 21 to 64, 100%, Medically Frail, adult w/ dependent children',
        'EFB - Adult Expansion, age 19 to 20, 100%, Medically Frail, adult w/ dependent children',
        'EFC - Adult Expansion, age 21 to 64, 133%, Medically Frail, adult w/ dependent children',
        'EFD - Adult Expansion, age 19 to 20, 133%, Medically Frail, adult w/ dependent children',
        'EFE - Adult Expansion, age 21 to 64, 100%, Medically Frail, adult w/ dependent children, Non-Trad',
        'EFF - Adult Expansion, age 19 to 20, 100%, Medically Frail, adult w/ dependent children, Non-Trad',
        'EFG - Adult Expansion, age 21 to 64, 133%, Medically Frail, adult w/ dependent children, Non-Trad',
        'EFH - Adult Expansion, age 19 to 20, 133%, Medically Frail, adult w/ dependent children, Non-Trad',
        'COV - Uninsured COVID-19 diagnostic testing',
        'WC0 - Community Transitions Waiver, Aged, SSI or Protected Groups',
        'WC2 - Community Transitions Waiver, Aged, income less than or equal to 100% FPL',
        'WC3 - Community Transitions Waiver, Aged, income over 300% FBR',
        'WC4 - Community Transitions Waiver, Aged, income less than or equal to 300% FBR',
        'WC5 - Community Transitions Waiver, Disabled, SSI or Protected Groups',
        'WC6 - Community Transitions waiver, Disabled, income less than or equal to 100% FPL',
        'WC7 - Community Transitions Waiver, Disabled, MWI',
        'WC8 - Community Transitions waiver, Blind or Disabled, income over 300% FBR',
        'WCA - Community Transitions waiver, Blind or Disabled, income less than or equal to 300% FBR',
        'QC0 - Community Transitions Waiver and QMB, Aged, SSI or Protected groups',
        'QC2 - Community Transitions Waiver and QMB, Aged, income less than or equal to 100% FPL',
        'QC4 - Community Transitions Waiver and QMB, Aged, special income group',
        'QC5 - Community Transitions Waiver and QMB, Disabled, SSI or Protected groups',
        'QC6 - Community Transitions Waiver and QMB, Disabled, with income less than or equal to 100% FPL',
        'QCA - Community Transitions Waiver and QMB, Blind or Disabled, special income group.',
        'EN1 - Nursing Home, age 21 to 64, adults without dependent children',
        'EN2 - Nursing Home, age 19 to 20, adults without dependent children',
        'EN3 - Nursing Home, age 21 to 64, adults without dependent children, ancillary',
        'EN4 - Nursing Home, age 19 to 20, adults without dependent children, ancillary',
        'EN5 - Nursing Home, age 21 to 64, adults with dependent children',
        'EN6 - Nursing Home, age 19 to 20, adults with dependent children',
        'EN7 - Nursing Home, age 21 to 64, adults with dependent children, ancillary',
        'EN8 - Nursing Home, age 19 to 20, adults with dependent children, ancillary',
        'LS1 - Limited Supports Waiver, Aged, SSI or Protected Groups',
        'LS2 - Limited Supports Waiver, Aged, income less than or equal to 100% FPL',
        'LS3 - Limited Supports Waiver, Aged, income over 300% FBR',
        'LS4 - Limited Supports Waiver, Aged, income less than or equal to 300% FBR',
        'LS5 - Limited Supports Waiver, Blind or Disabled, SSI or Protected Groups',
        'LS6 - Limited Supports Waiver, Disabled, income less than or equal to 100% FPL',
        'LS7 - Limited Supports Waiver, Disabled, MWI',
        'LS8 - Limited Supports Waiver, Blind or Disabled, income over 300% FBR',
        'LS9 - Limited Supports Waiver, Blind or Disabled, income less than or equal to 300% FBR',
        'QS1 - Limited Supports Waiver and QMB, Aged, SSI or Protected groups',
        'QS2 - Limited Supports Waiver and QMB, Aged, income less than or equal to 100% FPL',
        'QS4 - Limited Supports Waiver and QMB, Aged, special income group',
        'QS5 - Limited Supports Waiver and QMB, Blind or Disabled, SSI or Protected groups',
        'QS6 - Limited Supports Waiver and QMB, Disabled, with income less than or equal to 100% FPL',
        'QS9 - Limited Supports Waiver and QMB, Blind or Disabled, special income group',
        'C76 - Family Medicaid, Adult, spenddown',
        'II9 - Qualified Medicare Beneficiary, Medicare Part B-ID',
        'IN9 - Qualified Medicare Beneficiary, Medicare not aged or disabled',
        'ESB - Adult Expansion, age 21 to 64, 133%, ESI, adult w/ dependent children',
        'PCS - Parent Caretaker Relative Medicaid, Presumptive',
        'Q58 - Family Medicaid and QMB, Adult, 4-month spousal support',
        'Q59 - Family Medicaid and QMB, Adult, 12-month earned income increase',
        'Q76 - Family Medicaid and QMB, Adult, spenddown',
        'QA8 - Family Medicaid and QMB - Adult (Parent/Caretaker Relative)',
        'CHP - State CHIP',
        'A38 - Family Medicaid, Adult Parent/ Caretaker Relative',
        'A58 - Family Medicaid, Adult, 4-month spousal support increase',
        'A59 - Family Medicaid, Adult, 12-month transitional earned income increase',
        'E0B - Adult Expansion, age 21 to 64, 133%, adult w/ dependent children',
        'EP5 - Adult Expansion, age 21 to 64, 133%, Presumptive, adult w/ dependent children',
    ],
    values: [
        'A1',
        'A18',
        'A19',
        'A1A',
        'A21',
        'A22',
        'A23',
        'A31',
        'A32',
        'A35',
        'A36',
        'A37',
        'A4',
        'A42',
        'A43',
        'A44',
        'A5',
        'A51',
        'A52',
        'A55',
        'A57',
        'A61',
        'A62',
        'A63',
        'A64',
        'A65',
        'A66',
        'A67',
        'A68',
        'A69',
        'A7',
        'A8',
        'A80',
        'A81',
        'A82',
        'A83',
        'A84',
        'A94',
        'A95',
        'AA4',
        'AA5',
        'AB4',
        'AB5',
        'ABF',
        'AC3',
        'AC4',
        'AC8',
        'AC9',
        'ACF',
        'AD1',
        'AD2',
        'AD8',
        'AD9',
        'ADF',
        'AE1',
        'AE2',
        'AE8',
        'AE9',
        'AF1',
        'AF2',
        'AG1',
        'AH2',
        'AH3',
        'AH4',
        'AJ1',
        'AK1',
        'AUT',
        'B12',
        'B13',
        'B14',
        'B21',
        'B22',
        'B32',
        'B33',
        'B35',
        'B36',
        'B37',
        'B39',
        'B4',
        'B5',
        'B6',
        'B71',
        'B72',
        'B74',
        'B81',
        'B91',
        'BCF',
        'BDC',
        'BDW',
        'BYB',
        'C12',
        'C13',
        'C14',
        'C22',
        'C32',
        'C43',
        'C53',
        'C63',
        'C7',
        'C71',
        'C72',
        'C73',
        'C74',
        'C81',
        'C82',
        'C95',
        'CA5',
        'CB5',
        'CBF',
        'CCF',
        'CD1',
        'CD2',
        'CD3',
        'CD4',
        'CD5',
        'CDF',
        'CFC',
        'CI1',
        'CI2',
        'CI3',
        'CI4',
        'CI5',
        'CI6',
        'CI7',
        'CI8',
        'CI9',
        'CIP',
        'CT2',
        'CT3',
        'CT4',
        'CWA',
        'D1',
        'D2',
        'D3',
        'D4',
        'E',
        'EV',
        'EVQ',
        'I18',
        'IA1',
        'IA2',
        'IA3',
        'IA9',
        'IB1',
        'IB2',
        'IB9',
        'IC1',
        'IC2',
        'ICF',
        'ID1',
        'ID2',
        'ID3',
        'ID4',
        'ID5',
        'ID9',
        'IF1',
        'IF2',
        'IF5',
        'IF6',
        'IF7',
        'IF8',
        'IF9',
        'IFP',
        'IO9',
        'IP1',
        'MCC',
        'MP1',
        'MP2',
        'P19',
        'P82',
        'PC1',
        'PC2',
        'PC3',
        'PC4',
        'PC5',
        'PC6',
        'PC7',
        'PC8',
        'PCR',
        'PFM',
        'Q12',
        'Q13',
        'Q22',
        'Q32',
        'Q33',
        'Q35',
        'Q37',
        'Q42',
        'Q43',
        'Q44',
        'Q51',
        'Q53',
        'Q57',
        'Q71',
        'Q73',
        'Q82',
        'Q94',
        'Q95',
        'QA1',
        'QA2',
        'QA4',
        'QA5',
        'QA6',
        'QB1',
        'QB2',
        'QB3',
        'QB4',
        'QB5',
        'QB6',
        'QC1',
        'QC3',
        'QC8',
        'QC9',
        'QCC',
        'QD1',
        'QD2',
        'QD3',
        'QD4',
        'QD6',
        'QD8',
        'QD9',
        'QE1',
        'QE2',
        'QE3',
        'QE8',
        'QE9',
        'QF1',
        'QF2',
        'QG1',
        'QH2',
        'QN1',
        'QN2',
        'QN5',
        'QN6',
        'QP1',
        'QP2',
        'QP3',
        'QQ4',
        'QQ5',
        'QT2',
        'QT3',
        'QT4',
        'QWA',
        'RM1',
        'RM2',
        'TB',
        'TD1',
        'TD2',
        'TD3',
        'TD4',
        'TD5',
        'WAI',
        'WB1',
        'WB2',
        'WB3',
        'WB4',
        'WB5',
        'WB6',
        'WB7',
        'WD1',
        'WD2',
        'WD3',
        'WD4',
        'WD5',
        'WN1',
        'WN2',
        'WN3',
        'WN4',
        'WN5',
        'WN6',
        'WN7',
        'WN8',
        'WN9',
        'WP1',
        'WP2',
        'WP3',
        'WP4',
        'WP5',
        'WP6',
        'CWD',
        'QWD',
        'WAD',
        'E01',
        'E02',
        'E03',
        'E04',
        'E07',
        'E08',
        'EP1',
        'EP2',
        'EP3',
        'EP4',
        'EE1',
        'EE2',
        'EE3',
        'E05',
        'E06',
        'ES3',
        'ES4',
        'ES5',
        'ES6',
        'E09',
        'E0A',
        'ES7',
        'ES8',
        'ES9',
        'ESA',
        'EFA',
        'EFB',
        'EFC',
        'EFD',
        'EFE',
        'EFF',
        'EFG',
        'EFH',
        'COV',
        'WC0',
        'WC2',
        'WC3',
        'WC4',
        'WC5',
        'WC6',
        'WC7',
        'WC8',
        'WCA',
        'QC0',
        'QC2',
        'QC4',
        'QC5',
        'QC6',
        'QCA',
        'EN1',
        'EN2',
        'EN3',
        'EN4',
        'EN5',
        'EN6',
        'EN7',
        'EN8',
        'LS1',
        'LS2',
        'LS3',
        'LS4',
        'LS5',
        'LS6',
        'LS7',
        'LS8',
        'LS9',
        'QS1',
        'QS2',
        'QS4',
        'QS5',
        'QS6',
        'QS9',
        'C76',
        'II9',
        'IN9',
        'ESB',
        'PCS',
        'Q58',
        'Q59',
        'Q76',
        'QA8',
        'CHP',
        'A38',
        'A58',
        'A59',
        'E0B',
        'EP5',
    ]
}

const countyOptions = {
    labels: [
        'BEAVER',
        'BOX ELDER',
        'CACHE',
        'CARBON',
        'DAGGETT',
        'DAVIS',
        'DUCHESNE',
        'EMERY',
        'GARFIELD',
        'GRAND',
        'IRON',
        'JUAB',
        'KANE',
        'MILLARD',
        'MORGAN',
        'PIUTE',
        'RICH',
        'SALT LAKE',
        'SAN JUAN',
        'SANPETE',
        'SEVIER',
        'SUMMIT',
        'TOOELE',
        'UINTAH',
        'UTAH',
        'WASATCH',
        'WASHINGTON',
        'WAYNE',
        'WEBER',
        'OUT OF STATE',],
    values: [
        'CT100',
        'CT101',
        'CT102',
        'CT103',
        'CT104',
        'CT105',
        'CT106',
        'CT107',
        'CT108',
        'CT109',
        'CT110',
        'CT111',
        'CT112',
        'CT113',
        'CT114',
        'CT115',
        'CT116',
        'CT117',
        'CT118',
        'CT119',
        'CT120',
        'CT121',
        'CT122',
        'CT123',
        'CT124',
        'CT125',
        'CT126',
        'CT127',
        'CT128',
        'CT129',
    ]
}

export default function useOptions () {
    return {
        YNOptions,
        racOptions,
        countyOptions
    }
}